import type { OperationSpec } from '../operations/operations-types.ts';

export const contentOperationSpecs: OperationSpec[] = [{
	id: 'content.sync',
	name: 'content',
	aliases: [],
	group: 'Utilities',
	summary: 'Synchronize content checkouts or explicitly publish exact content commits to R2.',
	description: 'Sync compares Git, TreeDX, and publication refs. Publish accepts only paired content repositories and emits a read-back-verified, secret-free receipt.',
	provider: 'default',
	related: ['db', 'save', 'projects'],
	usage: 'treeseed content sync --project <project-id> [--branch <ref>] [--path <checkout>] [--plan] [--json]\n       treeseed content publish --team <team-id> --project <project-id> [--branch <ref>] [--channel <channel>] [--path <checkout>] (--plan|--apply --yes) [--json]\n       treeseed content publish --seed <name> [--project <slug>] [--branch <ref>] [--channel <channel>] (--plan|--apply --yes) [--json]',
	arguments: [{ name: 'action', description: 'Content action: sync or publish.', required: false }],
	options: [
		{ name: 'market', flags: '--market <id-or-url>', description: 'Configured Market profile or API URL.', kind: 'string' },
		{ name: 'seed', flags: '--seed <name>', description: 'Fetch and publish every paired content repository declared by a seed.', kind: 'string' },
		{ name: 'project', flags: '--project <project-id>', description: 'Project whose bound TreeDX repository is compared.', kind: 'string' },
		{ name: 'team', flags: '--team <team-id>', description: 'Owning team for publication keys.', kind: 'string' },
		{ name: 'branch', flags: '--branch <ref>', description: 'Publication branch to compare; defaults to staging.', kind: 'string' },
		{ name: 'channel', flags: '--channel <preview|staging|production>', description: 'R2 channel; inferred from the branch when omitted.', kind: 'string' },
		{ name: 'path', flags: '--path <checkout>', description: 'Local Git checkout; defaults to the current directory.', kind: 'string' },
		{ name: 'plan', flags: '--plan', description: 'Inspect exact refs without changing the checkout.', kind: 'boolean' },
		{ name: 'apply', flags: '--apply', description: 'Publish immutable objects and conditionally advance the selected R2 pointer.', kind: 'boolean' },
		{ name: 'yes', flags: '--yes', description: 'Confirm live R2 publication.', kind: 'boolean' },
		{ name: 'json', flags: '--json', description: 'Emit machine-readable output.', kind: 'boolean' },
	],
	examples: [
		'treeseed content sync --project project_123 --branch staging --plan --json',
		'treeseed content sync --project project_123 --branch staging',
		'treeseed content publish --team team_123 --project project_123 --branch staging --plan --json',
	],
	notes: [
		'Live sync fetches and fast-forwards only after local, upstream, and TreeDX commits match the plan.',
		'Dirty, detached, missing, stale, or diverged repositories fail closed and no local work is discarded.',
	],
	help: {
		longSummary: ['Content sync compares exact local, TreeDX, and upstream Git revisions before any repository-native content movement.'],
		whenToUse: ['Use plan mode to diagnose publication-ref drift, then use live sync only when the local checkout can safely fast-forward.'],
		beforeYouRun: ['Select the bound project and ensure the local checkout has no uncommitted changes or detached branch state.'],
		automationNotes: ['The command fails closed on stale, missing, dirty, detached, or diverged state and never discards local work.'],
	},
	helpVisible: true,
	helpFeatured: false,
	executionMode: 'handler',
	handlerName: 'content',
}];
