import type { OperationSpec } from '../operations/operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from '../operations/operations-registry-support.ts';

export const scenesAndGuaranteesOperationSpecs: OperationSpec[] = [
	{
			id: 'scene',
			name: 'scene',
			aliases: [],
			group: 'Validation',
			summary: 'Inspect the Treeseed scene workflow testing and video platform.',
			description: 'Reports readiness for, validates, plans, and runs the manifest-driven acceptance test harness and demo/training video generator.',
			provider: 'default',
			related: ['dev', 'seed', 'ready', 'test:e2e'],
			usage: 'treeseed scene [status] [--json]\n       treeseed scene validate <scene.yaml> [--json]\n       treeseed scene plan <scene.yaml> [--environment local|staging|prod] [--json]\n       treeseed scene run <scene.yaml> [--environment local|staging|prod] [--record] [--mode acceptance|demo|training|record-only] [--device desktop|tablet|mobile|all] [--json]\n       treeseed scene visual-audit <scene.yaml> [--environment local|staging|prod] [--roles anonymous,owner,admin,member] [--device desktop|tablet|mobile|all] [--path-root /app,/auth,/market] [--path /app/**] [--exclude-path **/delete] [--full-page] [--fresh-dev] [--review|--no-review] [--review-detail summary|standard|full] [--max-findings <n>] [--json]\n       treeseed scene inspect <run-id-or-path> [--step <step-id>] [--json]\n       treeseed scene resume <run-id-or-path> --from-checkpoint <checkpoint-id> [--json]\n       treeseed scene render <scene.yaml> --from <run-id-or-path> [--renderer remotion] [--format mp4] [--mode demo|training|failure-review|chapter|diagram-only] [--device <profile>] [--composition <id>] [--chapter <chapter-id>] [--output <path>] [--json]\n       treeseed scene training <scene.yaml> --from <run-id-or-path> [--format json|markdown|vtt|srt] [--json]\n       treeseed scene evidence <scene.yaml> --from <run-id-or-path> [--target local|ci|release] [--bundle metadata-only|sanitized] [--json]\n       treeseed scene publish <scene.yaml> --from <run-id-or-path> [--target local|release] [--redaction-policy <path>] [--json]\n       treeseed scene publish-plan <scene.yaml> --from <run-id-or-path> [--target docs,training,release-evidence,artifact-store] [--json]\n       treeseed scene export <scene.yaml> --from <run-id-or-path> [--target docs,training,release-evidence,artifact-store] [--json]',
			arguments: [
				{ name: 'action', description: 'Scene action. Use status, validate, plan, run, visual-audit, inspect, resume, render, training, evidence, publish, publish-plan, or export.', required: false },
				{ name: 'scene', description: 'Scene manifest path or bare scene id under scenes/.', required: false },
			],
			options: [
				{ name: 'environment', flags: '--environment <scope>', description: 'Environment to select for scene planning or execution.', kind: 'enum', values: ['local', 'staging', 'prod'] },
				{ name: 'record', flags: '--record', description: 'Record Playwright video even when the scene artifact settings do not request video.', kind: 'boolean' },
				{ name: 'sceneArtifacts', flags: '--scene-artifacts <mode>', description: 'Choose scene evidence mode.', kind: 'enum', values: ['full', 'screenshots'] },
				{ name: 'noSceneVideo', flags: '--no-scene-video', description: 'Alias for --scene-artifacts screenshots.', kind: 'boolean' },
				{ name: 'mode', flags: '--mode <mode>', description: 'Override run mode for scene run, or render mode for scene render.', kind: 'string' },
				{ name: 'device', flags: '--device <profile|all>', description: 'Run or render a scene with a named device profile such as desktop, tablet, mobile, or all profiles for a device matrix run.', kind: 'string' },
				{ name: 'roles', flags: '--roles <roles>', description: 'Comma-separated visual audit roles such as anonymous, owner, admin, member.', kind: 'string' },
				{ name: 'pathRoot', flags: '--path-root <roots>', description: 'Comma-separated visual audit path roots such as /app,/auth,/market.', kind: 'string' },
				{ name: 'path', flags: '--path <globs>', description: 'Comma-separated or repeatable visual audit route include globs such as /app/projects/** or **/settings.', kind: 'string', repeatable: true },
				{ name: 'excludePath', flags: '--exclude-path <globs>', description: 'Comma-separated or repeatable visual audit route exclude globs such as **/delete or /auth/callback/**.', kind: 'string', repeatable: true },
				{ name: 'fullPage', flags: '--full-page', description: 'Also capture full-page screenshots during visual audit for debugging.', kind: 'boolean' },
				{ name: 'freshDev', flags: '--fresh-dev', description: 'Restart the local managed dev instance before visual audit to avoid stale Vite/module graph failures.', kind: 'boolean' },
				{ name: 'review', flags: '--review', description: 'Generate deterministic visual audit findings, contact sheets, and an agent repair brief.', kind: 'boolean' },
				{ name: 'noReview', flags: '--no-review', description: 'Capture screenshots only and skip visual audit review outputs.', kind: 'boolean' },
				{ name: 'reviewDetail', flags: '--review-detail <detail>', description: 'Visual audit review detail level: summary, standard, or full.', kind: 'string' },
				{ name: 'maxFindings', flags: '--max-findings <n>', description: 'Maximum number of detailed visual audit findings to include.', kind: 'string' },
				{ name: 'step', flags: '--step <step-id>', description: 'Select a single step when inspecting a scene run.', kind: 'string' },
				{ name: 'fromCheckpoint', flags: '--from-checkpoint <checkpoint-id>', description: 'Resume a scene run from a resumable checkpoint.', kind: 'string' },
				{ name: 'from', flags: '--from <run-id-or-path>', description: 'Source scene run id or artifact path for render-only video, training output, evidence generation, evidence publishing, publish planning, or local export.', kind: 'string' },
				{ name: 'target', flags: '--target <target>', description: 'Evidence target, publish target, or comma-separated Phase 11 publication targets: docs, training, release-evidence, artifact-store.', kind: 'string' },
				{ name: 'bundle', flags: '--bundle <policy>', description: 'Evidence bundle policy for scene evidence generation.', kind: 'enum', values: ['metadata-only', 'sanitized'] },
				{ name: 'redactionPolicy', flags: '--redaction-policy <path>', description: 'JSON or YAML redaction policy for scene evidence publishing.', kind: 'string' },
				{ name: 'renderer', flags: '--renderer <renderer>', description: 'Renderer plugin to use for scene render. Phase 11 keeps Remotion adapter-hosted and replaceable.', kind: 'string' },
				{ name: 'format', flags: '--format <format>', description: 'Rendered video format for render, or training output format for scene training.', kind: 'string' },
				{ name: 'composition', flags: '--composition <id>', description: 'Remotion composition id to render.', kind: 'string' },
				{ name: 'chapter', flags: '--chapter <chapter-id>', description: 'Render only one chapter from the source scene run.', kind: 'string' },
				{ name: 'output', flags: '--output <path>', description: 'Output path for the rendered video.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: [
				'treeseed scene',
				'trsd scene status --json',
				'trsd scene validate scenes/market-project-deploy-demo.yaml --json',
				'trsd scene plan market-project-deploy-demo --environment local --json',
				'trsd scene run market-project-deploy-demo --environment local --record --json',
				'trsd scene run market-project-deploy-demo --environment local --record --device desktop --json',
				'trsd scene run market-project-deploy-demo --environment local --record --device tablet --json',
				'trsd scene run market-project-deploy-demo --environment local --record --device mobile --json',
				'trsd scene run market-project-deploy-demo --environment local --record --device all --json',
				'trsd scene visual-audit scenes/site-visual-audit.yaml --environment local --roles anonymous,owner,admin,member --device all --json',
				'trsd scene visual-audit scenes/site-visual-audit.yaml --environment local --fresh-dev --roles anonymous,owner,admin,member --device all --review-detail full --json',
				'trsd scene visual-audit scenes/site-visual-audit.yaml --environment local --roles owner --device desktop --path-root /app --review-detail full --json',
				'trsd scene visual-audit scenes/site-visual-audit.yaml --environment local --roles owner --device mobile --path /app/projects/** --exclude-path **/delete --review-detail full --json',
				'trsd scene visual-audit scenes/site-visual-audit.yaml --environment local --roles anonymous --device all --no-review --json',
				'trsd scene inspect .treeseed/scenes/runs/market-project-deploy-demo/20260614T120000Z-run123 --step queue-staging-deploy --json',
				'trsd scene resume .treeseed/scenes/runs/market-project-deploy-demo/20260614T120000Z-run123 --from-checkpoint open-projects --json',
				'trsd scene render market-project-deploy-demo --from 20260614T120000Z-run123 --renderer remotion --format mp4 --json',
				'trsd scene render market-project-deploy-demo --from 20260614T120000Z-run123 --device desktop --renderer remotion --format mp4 --json',
				'trsd scene render market-project-deploy-demo --from 20260614T120000Z-run123 --mode failure-review --json',
				'trsd scene render market-project-deploy-demo --from 20260614T120000Z-run123 --mode diagram-only --json',
				'trsd scene training market-project-deploy-demo --from 20260614T120000Z-run123 --format vtt --json',
				'trsd scene evidence market-project-deploy-demo --from 20260614T120000Z-run123 --target ci --bundle sanitized --json',
				'trsd scene publish market-project-deploy-demo --from 20260614T120000Z-run123 --target local --json',
				'trsd scene publish-plan market-project-deploy-demo --from 20260614T120000Z-run123 --target docs,training,release-evidence --json',
				'trsd scene export market-project-deploy-demo --from 20260614T120000Z-run123 --target docs,training --json',
			],
			help: {
				workflowPosition: 'validate',
				longSummary: [
					'Scene is the command surface for the central TreeSeed acceptance test harness and demo / educational video generator.',
					'Phase 11 validates YAML scene manifests, compiles deterministic plans with plugin diagnostics, prepares Treeseed environments, runs Playwright workflows with debugging artifacts, supports long workflow checkpoints, inspect, resume, renders Remotion videos from existing evidence, renders typed animated diagrams, generates deterministic training outputs, writes evidence manifests plus sanitized bundles, publishes redacted local/release evidence bundles, and produces publication plans plus local exports from those redacted bundles.',
				],
				whenToUse: [
					'Use this command to verify that the installed Treeseed CLI and SDK expose the scene platform foundation.',
					'Use validate and plan before browser execution when scene contracts are still being authored.',
					'Use run for browser workflows that need Treeseed setup, trace, screenshot, console, network, timeline, run JSON, Markdown report artifacts, progress events, and checkpoints.',
					'Use `--device desktop`, `--device tablet`, `--device mobile`, or `--device all` to produce separate walkthroughs for different interfaces from the same scene.',
					'Use inspect and resume when a long scene fails late or needs to continue from a durable checkpoint.',
					'Use render to turn a previous run into a demo, training, chapter, failure-review, or diagram-only MP4 without rerunning the browser workflow.',
					'Use training to generate captions, transcripts, narration scripts, glossary artifacts, and chapter clip manifests from existing scene evidence without AI or TTS.',
					'Use evidence to generate a CI- or release-ready manifest and sanitized local bundle from existing run artifacts.',
					'Use publish to create a deny-by-default redacted local or release evidence bundle without external publication.',
					'Use publish-plan to review docs, training, release-evidence, and artifact-store publication intent without external mutation.',
					'Use export to copy already-redacted publish artifacts into local docs, training, and release-evidence export folders.',
					'Use `--json` when an agent, CI check, or future workflow needs stable capability output.',
				],
				beforeYouRun: [
					'No Treeseed project is required for Phase 0 status because the command reports installed platform capability only.',
				],
				outcomes: [
					'Prints scene platform status, validates manifests, emits deterministic plugin-aware plan reports, runs Playwright workflows, inspects run artifacts, resumes from checkpoints, renders Remotion MP4s, generates training artifacts, writes evidence manifests and sanitized bundles, publishes redacted evidence bundles, or creates Phase 11 publication plans and local exports.',
					'Can start managed local dev and apply seeds only when explicitly requested by the scene manifest; render, training, evidence, publish, publish-plan, and export are downstream of existing artifacts and do not perform browser execution, interactive auth, dynamic plugin discovery, or provider mutation.',
				],
				automationNotes: [
					'Run and resume emit newline-delimited JSON progress events followed by one final JSON report when `--json` is selected.',
					'The status JSON report includes phase, status, commandSurface, sdkExports, capabilities, deferredDependencies, and nextPhase.',
					'Unsupported runtime actions and assertions fail clearly with phase-specific diagnostics.',
					'Render falls back to screenshot slideshow output when a source run has screenshots but no Playwright video.',
					'Typed diagrams are validated by the SDK and rendered downstream from existing scene evidence; rendering still does not rerun workflows.',
					'Evidence publishing writes local and release-target redacted bundles only; it does not mutate external providers or publish to remote stores.',
					'Phase 11 publication plans write reconciliation intent records with action `plan-only`; remote publication apply is deferred.',
				],
				relatedDetails: [
					related('dev', 'Scene runs reuse managed dev instance discovery and startup for local workflow tests.'),
					related('seed', 'Scene setup uses seed validation and explicit apply paths for deterministic data.'),
					related('ready', 'Scene setup reuses readiness checks before browser execution.'),
				],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'scene',
		},
	{
			id: 'guarantees',
			name: 'guarantees',
			aliases: [],
			group: 'Validation',
			summary: 'Validate, plan, run, and export TreeSeed product guarantees.',
			description: 'Discovers package-local guarantee YAML manifests, validates lowercase taxonomy and dependency graphs, plans focused or release-wide guarantee coverage, executes active guarantees, and exports generated CSV/JSON/Markdown reports from the canonical YAML source.',
			provider: 'default',
			related: ['scene', 'release', 'ready'],
			usage: 'treeseed guarantees [status] [--json]\n       treeseed guarantees validate [--type <type>] [--subtype <subtype>] [--gate <gate>] [--json]\n       treeseed guarantees audit-journeys [--owner-package <package>] [--write-report <path>] [--json]\n       treeseed guarantees plan [--environment local|staging|prod] [--type <type>] [--subtype <subtype>] [--gate <gate>] [--json]\n       treeseed guarantees export [--format csv|json|markdown] [--output <path>] [--type <type>] [--subtype <subtype>] [--json]\n       treeseed guarantees run [--environment local|staging|prod] [--gate <gate>] [--include-planned] [--json]',
			arguments: [
				{ name: 'action', description: 'Guarantee action. Use status, validate, audit-journeys, plan, export, or run.', required: false },
			],
			options: [
				{ name: 'environment', flags: '--environment <scope>', description: 'Environment to select for guarantee planning or execution.', kind: 'enum', values: ['local', 'staging', 'prod'] },
				{ name: 'type', flags: '--type <type>', description: 'Filter guarantees by lowercase type such as project or capacity.', kind: 'string' },
				{ name: 'subtype', flags: '--subtype <subtype>', description: 'Filter guarantees by lowercase subtype such as question or assignment.', kind: 'string' },
				{ name: 'gate', flags: '--gate <gate>', description: 'Filter guarantees by gate.', kind: 'enum', values: ['smoke', 'core', 'release', 'security', 'migration', 'demo', 'backlog', 'future'] },
				{ name: 'ownerPackage', flags: '--owner-package <package>', description: 'Filter guarantees by one owner package or a comma-separated owner list such as @treeseed/api,@treeseed/agent.', kind: 'string' },
				{ name: 'sceneBacked', flags: '--scene-backed', description: 'Filter to guarantees with an executable scene manifest.', kind: 'boolean' },
				{ name: 'status', flags: '--status <status>', description: 'Filter guarantees by status.', kind: 'enum', values: ['active', 'planned', 'blocked', 'backlog', 'deprecated'] },
				{ name: 'id', flags: '--id <id>', description: 'Filter by guarantee id. Comma-separated values are accepted.', kind: 'string' },
				{ name: 'journeyIndex', flags: '--journey-index <index>', description: 'Filter by journey index. Comma-separated values are accepted.', kind: 'string' },
				{ name: 'format', flags: '--format <format>', description: 'Export format for guarantees export.', kind: 'enum', values: ['csv', 'json', 'markdown'] },
				{ name: 'output', flags: '--output <path>', description: 'Write generated export to this path. Without --output, export prints to stdout.', kind: 'string' },
				{ name: 'writeReport', flags: '--write-report <path>', description: 'Write a guarantee journey audit report to this workspace-relative path.', kind: 'string' },
				{ name: 'includePlanned', flags: '--include-planned', description: 'Include planned/backlog guarantees in run reports as skipped entries.', kind: 'boolean' },
				{ name: 'noDependencies', flags: '--no-dependencies', description: 'Do not expand guarantee dependencies in plan or run.', kind: 'boolean' },
				{ name: 'record', flags: '--record', description: 'Record scene/video evidence while running guarantees.', kind: 'boolean' },
				{ name: 'sceneArtifacts', flags: '--scene-artifacts <mode>', description: 'Choose scene evidence mode.', kind: 'enum', values: ['full', 'screenshots'] },
				{ name: 'noSceneVideo', flags: '--no-scene-video', description: 'Alias for --scene-artifacts screenshots.', kind: 'boolean' },
				{ name: 'device', flags: '--device <device>', description: 'Limit scene execution to one device profile when supported.', kind: 'string' },
				{ name: 'evidenceTarget', flags: '--evidence-target <target>', description: 'Evidence target for guarantee runs.', kind: 'enum', values: ['local', 'ci', 'release'] },
				{ name: 'json', flags: '--json', description: 'Emit structured JSON.', kind: 'boolean' },
			],
			examples: [
				example('treeseed guarantees validate --json', 'Validate all guarantees', 'Checks taxonomy, dependencies, verifier references, and package ownership.'),
				example('treeseed guarantees plan --type project --subtype question --json', 'Plan focused guarantees', 'Plans only project question guarantees plus dependencies.'),
				example('treeseed guarantees run --owner-package @treeseed/agent --environment local --json', 'Run active agent guarantees', 'Executes active agent-owned guarantees and writes evidence under .treeseed/guarantees/runs.'),
				example('treeseed guarantees export --format csv --output .treeseed/generated/guarantees/guarantees.csv --json', 'Generate CSV', 'Creates a CSV report from canonical YAML manifests.'),
			],
			help: {
				longSummary: [
					'Guarantees are TreeSeed product contracts backed by package-local YAML manifests, scene workflows, API acceptance verifier references, and evidence reports.',
					'The command validates the guarantee registry, plans focused or release-wide execution, runs active guarantees, and exports generated reports from the canonical YAML source.',
				],
				whenToUse: [
					'Use this before completing work that changes a product promise.',
					'Use type/subtype filters for fast spot checks while developing one system area.',
					'Use full validation and release planning before release work.',
				],
				beforeYouRun: [
					'Make sure package-local guarantee YAML files use lowercase type and subtype values.',
					'Start the local platform before running local scene-backed guarantees.',
					'Use --json for automation and for preserving diagnostics in CI logs.',
				],
				automationNotes: [
					'Filtered validate, plan, export, and run commands accept canonical lowercase --type and --subtype values.',
					'Run reports are written under .treeseed/guarantees/runs unless an explicit output target is provided.',
					'Release guarantees are enforced by the release command; do not bypass them from CI workflows.',
				],
				warnings: [
					'Guarantee YAML is the source of truth. Generated CSV files must not be hand-edited.',
					'Release workflows must call the release CLI, which owns guarantee gating.',
				],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'guarantees',
		},
];
