import type { OperationSpec } from '../../operations/operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from '../../operations/operations-registry-support.ts';

export const marketProjectsOperationSpecs: OperationSpec[] = [
	{
			id: 'market.registry',
			name: 'market',
			aliases: [],
			group: 'Utilities',
			summary: 'Manage configured Treeseed API endpoints.',
			description: 'List, add, select, remove, and inspect API profiles stored in local machine configuration.',
			provider: 'default',
			related: ['auth:login', 'teams', 'projects'],
			usage: 'treeseed market [list|add|use|remove|status]',
			arguments: [{ name: 'action', description: 'Market action.', required: false }],
			options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
				{ name: 'label', flags: '--label <label>', description: 'Display label for market add.', kind: 'string' },
				{ name: 'kind', flags: '--kind <kind>', description: 'Market kind for market add.', kind: 'enum', values: ['central', 'specialized'] },
				{ name: 'team', flags: '--team <team-id>', description: 'Team id for a specialized market profile.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: ['treeseed market list', 'treeseed market add enterprise https://market.example.com', 'treeseed market use central'],
			help: {
				longSummary: ['Market manages local Treeseed API profiles. It never serves market behavior itself; it only selects endpoints the SDK market client should call.'],
				whenToUse: ['Use this when you need to add an enterprise market, switch back to central, or inspect which market endpoint CLI commands will target.'],
				beforeYouRun: ['Decide whether you are managing the always-available central profile or a team-specific specialized market profile.'],
				automationNotes: ['Use `--json` when scripts need the active market id, URL, and configured profiles.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'market',
		},
	{
			id: 'market.teams',
			name: 'teams',
			aliases: [],
			group: 'Utilities',
			summary: 'Inspect teams from the selected market.',
			description: 'List teams, select a team context, and inspect team membership through the API client.',
			provider: 'default',
			related: ['market', 'auth:login', 'projects'],
			usage: 'treeseed teams [list|use|members]',
			arguments: [{ name: 'action', description: 'Teams action.', required: false }],
			options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
				{ name: 'team', flags: '--team <team-id>', description: 'Team id for member lookup.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: ['treeseed teams list', 'treeseed teams members team_123'],
			help: {
				longSummary: ['Teams reads team membership data from the selected API using the SDK market client.'],
				whenToUse: ['Use this after login to confirm team membership or inspect who belongs to a market-owned team.'],
				beforeYouRun: ['Authenticate to the selected market with `treeseed auth:login --market <id>` before reading private team data.'],
				automationNotes: ['Use `--json` for scripts that need stable team or member arrays.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'teams',
		},
	{
			id: 'market.projects',
			name: 'projects',
			aliases: [],
			group: 'Utilities',
			summary: 'Inspect projects from the selected API.',
			description: 'List projects and inspect team access while project launch and repository management are rebuilt on Services capability bindings.',
			provider: 'default',
			related: ['market', 'teams', 'config'],
			usage: 'treeseed projects [list|access]',
			arguments: [
				{ name: 'action', description: 'Projects action.', required: false },
				{ name: 'project-id', description: 'Project id for access inspection.', required: false },
			],
			options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
				{ name: 'team', flags: '--team <team-id>', description: 'Limit project list to a team.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: [
				'treeseed projects list',
				'treeseed projects access project_123',
			],
			help: {
				longSummary: ['Projects reads project identity, architecture, and access state from the selected API.'],
				whenToUse: ['Use this to inspect project identity and access while project creation and repository connection are intentionally unavailable.'],
				beforeYouRun: ['Authenticate to the selected API before reading private project data.'],
				automationNotes: ['Use `--json` to capture stable project data.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'projects',
		},
];
