import type { OperationSpec } from '../../operations/operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from '../../operations/operations-registry-support.ts';

export const treedxAndPacksOperationSpecs: OperationSpec[] = [
	{
			id: 'market.db',
			name: 'db',
			aliases: [],
			group: 'Utilities',
			summary: 'Manage team TreeDX knowledge-library bindings.',
			description: 'Inspect, provision, connect, mirror, share, and bind TreeDX libraries, and plan TreeDX image policy.',
			provider: 'default',
			related: ['teams', 'projects', 'capacity'],
			usage: 'treeseed db [status|provision|connect|mirrors|shares|library|topology|image]',
			arguments: [{ name: 'action', description: 'TreeDX action.', required: false }],
			options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
				{ name: 'team', flags: '--team <team-id>', description: 'Team id for status, provisioning, mirrors, and shares.', kind: 'string' },
				{ name: 'project', flags: '--project <project-id>', description: 'Project id for library binding and topology inspection.', kind: 'string' },
				{ name: 'public', flags: '--public', description: 'Use public federation posture for provisioning or sharing.', kind: 'boolean' },
				{ name: 'selfHosted', flags: '--self-hosted', description: 'Connect a self-hosted TreeDX URL as the primary binding.', kind: 'boolean' },
				{ name: 'url', flags: '--url <url>', description: 'TreeDX base URL for connect/provision.', kind: 'string' },
				{ name: 'registryUrl', flags: '--registry-url <url>', description: 'Optional TreeDX registry URL.', kind: 'string' },
				{ name: 'image', flags: '--image <image-ref>', description: 'TreeDX container image ref, default treeseed/treedx:latest.', kind: 'string' },
				{ name: 'name', flags: '--name <name>', description: 'Mirror display name.', kind: 'string' },
				{ name: 'targetUrl', flags: '--target-url <url>', description: 'Mirror target URL.', kind: 'string' },
				{ name: 'targetKind', flags: '--target-kind <kind>', description: 'Mirror target kind such as git or treedx.', kind: 'string' },
				{ name: 'direction', flags: '--direction <mode>', description: 'Mirror direction: pull, push, or bidirectional.', kind: 'string' },
				{ name: 'scope', flags: '--scope <scope>', description: 'Share scope: team, library, or public_federation.', kind: 'string' },
				{ name: 'targetTeam', flags: '--target-team <team-id>', description: 'Target team id for a team share.', kind: 'string' },
				{ name: 'library', flags: '--library <library-id>', description: 'TreeDX library id for project binding or share.', kind: 'string' },
				{ name: 'instance', flags: '--instance <instance-id>', description: 'TreeDX instance id for project binding.', kind: 'string' },
				{ name: 'repository', flags: '--repository <repo-id>', description: 'TreeDX repository id for project binding.', kind: 'string' },
				{ name: 'contentRepositoryUrl', flags: '--content-repository-url <url>', description: 'Linked GitHub content repository URL.', kind: 'string' },
				{ name: 'branch', flags: '--branch <branch>', description: 'TreeDX branch/ref for source-build planning. Defaults to staging.', kind: 'string' },
				{ name: 'workflow', flags: '--workflow <file>', description: 'TreeDX GitHub Actions workflow file for production image publication.', kind: 'string' },
				{ name: 'syncConfig', flags: '--sync-config', description: 'Sync package image credentials from Treeseed config into the package GitHub environment.', kind: 'boolean' },
				{ name: 'plan', flags: '--plan', description: 'Print the TreeDX image plan without dispatching GitHub Actions.', kind: 'boolean' },
				{ name: 'execute', flags: '--execute', description: 'Dispatch the TreeDX production image workflow when policy allows image publication.', kind: 'boolean' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: [
				'treeseed db status --team team_123',
				'treeseed db provision --team team_123',
				'treeseed db provision --team team_123 --public',
				'treeseed db connect --team team_123 --url https://treedx.example.com --self-hosted',
				'treeseed db mirrors --team team_123 --name customer-copy --target-url https://treedx.customer.example',
				'treeseed db shares --team team_123 --library team/project --public',
				'treeseed db library --project project_123 --library team/project',
				'treeseed db topology --project project_123 --json',
				'treeseed db image --branch staging --plan --json',
				'treeseed db image --branch main --plan --json',
			],
			help: {
				longSummary: ['TreeDX commands manage the Treeseed control-plane records that bind each team to one primary knowledge-library instance, bind project content to TreeDX libraries, and plan deterministic TreeDX source-build or production image behavior.'],
				whenToUse: ['Use this when provisioning a private TreeDX, attaching a public team to federation, creating mirror/share records, inspecting project content/site/project topology, or publishing the TreeDX image that the API app should reconcile.'],
				beforeYouRun: ['Log in to the selected Treeseed API first for team/project actions. For `db image --execute`, configure GitHub credentials through Treeseed-managed config. Do not pass secrets on the command line; TreeDX credentials belong in host secret managers or encrypted config.'],
				automationNotes: ['Use `--json` for stable TreeDX binding, mirror, share, library, topology, and image policy records. TreeDX, API, operations runner, and agent staging services use source builds. Production image refs are semantic release artifacts.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'db',
		},
	{
			id: 'market.packs',
			name: 'packs',
			aliases: [],
			group: 'Utilities',
			summary: 'Build and download repository-native knowledge packs.',
			description: 'List, build, inspect, and download immutable packs from exact TreeDX book snapshots through the selected TreeSeed API.',
			provider: 'default',
			related: ['db', 'projects'],
			usage: 'treeseed packs [list|build|status|download] [build-id]',
			arguments: [{ name: 'action', description: 'Packs action.', required: false }],
			options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Select the configured API that owns the team.', kind: 'string' },
				{ name: 'team', flags: '--team <team-id>', description: 'Team whose selected books are packed.', kind: 'string' },
				{ name: 'collection', flags: '--collection <collection-id>', description: 'Saved book collection to build.', kind: 'string' },
				{ name: 'books', flags: '--books <book-id,...>', description: 'Comma-separated book IDs for an ad hoc build.', kind: 'string' },
				{ name: 'output', flags: '--output <directory>', description: 'Download directory; defaults to .treeseed/downloads.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: ['treeseed packs list --team team_123', 'treeseed packs build --team team_123 --books book-a,book-b', 'treeseed packs status build_123', 'treeseed packs download build_123'],
			help: {
					longSummary: ['Packs are immutable exports of explicitly selected repository-native books, pages, and authorized graph relationships at exact Git and TreeDX revisions.'],
				whenToUse: ['Use this to build a single-book, selected-book, or saved-collection context artifact without expanding to externally related books.'],
				beforeYouRun: ['Log in to the owning API. Building requires knowledge:build-packs; no passphrase or provider credential is accepted by this command.'],
				automationNotes: ['Use `--json` to capture the build, operation, source closure, digest, and downloaded path. Poll `status` until the operations runner completes the build.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'packs',
		},
];
