import type { OperationSpec } from '../../operations/operations-types.ts';

export const knowledgeOperationSpecs: OperationSpec[] = [{
	id: 'market.knowledge',
	name: 'knowledge', aliases: [], group: 'Knowledge', summary: 'Operate governed knowledge workspaces, reviews, and publication.',
	description: 'Creates and inspects TreeDX workspaces, records independent editorial reviews, and publishes only approved exact revisions.',
	provider: 'default',
	related: ['governance', 'capacity'],
	usage: 'treeseed knowledge <action> --project <project-id> [options] [--json]',
	arguments: [{ name: 'action', description: 'workspace-create, workspace-status, review-submit, review-show, review-comment, review-resolve, editorial-review, review-decide, review-publish, or publication-status.', required: true }],
	options: [
		{ name: 'market', flags: '--market <market>', description: 'Market profile.', kind: 'string' },
		{ name: 'project', flags: '--project <project-id>', description: 'Project id.', kind: 'string' },
		{ name: 'team', flags: '--team <team-id>', description: 'Team id.', kind: 'string' },
		{ name: 'workspace', flags: '--workspace <workspace-id>', description: 'Knowledge workspace id.', kind: 'string' },
		{ name: 'review', flags: '--review <review-id>', description: 'Knowledge review id.', kind: 'string' },
		{ name: 'comment', flags: '--comment <comment-id>', description: 'Knowledge review comment id.', kind: 'string' },
		{ name: 'version', flags: '--version <version>', description: 'Inspected workspace or comment version.', kind: 'string' },
		{ name: 'path', flags: '--path <path>', description: 'Changed content path for a review comment.', kind: 'string' },
		{ name: 'message', flags: '--message <text>', description: 'Commit or review message.', kind: 'string' },
		{ name: 'notes', flags: '--notes <text>', description: 'Review decision notes.', kind: 'string' },
		{ name: 'decision', flags: '--decision <approve|request-changes>', description: 'Review decision.', kind: 'enum', values: ['approve', 'request-changes'] },
		{ name: 'kind', flags: '--kind <technical|audience|graph>', description: 'Editorial review kind.', kind: 'enum', values: ['technical', 'audience', 'graph'] },
		{ name: 'disposition', flags: '--disposition <approved|changes-requested>', description: 'Editorial review disposition.', kind: 'enum', values: ['approved', 'changes-requested'] },
		{ name: 'result', flags: '--result <json>', description: 'Structured editorial review result with criteria.', kind: 'string' },
		{ name: 'contextDigest', flags: '--context-digest <digest>', description: 'Compiled editorial context digest.', kind: 'string' },
		{ name: 'simulateHuman', flags: '--simulate-human', description: 'Record AI-operated human simulation provenance.', kind: 'boolean' },
		{ name: 'simulationPurpose', flags: '--simulation-purpose <text>', description: 'Purpose of simulated-human testing.', kind: 'string' },
		{ name: 'workday', flags: '--workday <id>', description: 'Active workday id.', kind: 'string' },
		{ name: 'assignment', flags: '--assignment <id>', description: 'Related assignment id.', kind: 'string' },
		{ name: 'reason', flags: '--reason <text>', description: 'Evidence-based reason for a simulated decision.', kind: 'string' },
		{ name: 'production', flags: '--production', description: 'Request explicitly authorized simulated-human production approval.', kind: 'boolean' },
		{ name: 'yes', flags: '--yes', description: 'Confirm a binding review or publication action.', kind: 'boolean' },
		{ name: 'json', flags: '--json', description: 'Emit JSON.', kind: 'boolean' },
	], examples: ['treeseed knowledge workspace-create --project project_123 --json', 'treeseed knowledge review-decide --review review_123 --decision approve --version 2 --simulate-human --workday run_123 --reason "Reviews passed" --yes --json'],
	help: {
		longSummary: ['Knowledge provides the authenticated editorial workspace, review, approval, and exact-revision publication cockpit.'],
		whenToUse: ['Use it after evidence and drafting work to inspect a workspace, submit independent reviews, approve an exact revision, or inspect publication closure.'],
		beforeYouRun: ['Authenticate to the selected market and inspect the exact workspace revision, context digest, reviews, and unresolved comments before any binding action.'],
		automationNotes: ['Every binding action requires confirmation. Simulated-human actions require explicit provenance and never widen the authenticated principal\'s authority.'],
	},
	helpVisible: true,
	helpFeatured: false,
	executionMode: 'handler', handlerName: 'knowledge',
}];
