import type { TreeseedOperationSpec } from './operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from './operations-registry-support.ts';

export const packageAndWorkflowOperationSpecs: TreeseedOperationSpec[] = [
	{
			id: 'workflow.dispatch',
			name: 'workflow',
			aliases: [],
			group: 'Utilities',
			summary: 'Plan or dispatch a GitHub Actions workflow through reconciliation.',
			description: 'Triggers a workflow_dispatch run through the github-workflow-dispatch reconcile adapter so package and root workflows can be tested without pushing commits.',
			provider: 'default',
			related: ['package', 'gh', 'ci'],
			usage: 'treeseed workflow dispatch --repo <owner/name> --workflow <file> [--branch <ref>] [--input key=value]... [--execute] [--wait] [--json]',
			arguments: [{ name: 'action', description: 'Workflow action. Use dispatch.', required: false }],
			options: [
				{ name: 'repo', flags: '--repo <owner/name>', description: 'GitHub repository that owns the workflow.', kind: 'string' },
				{ name: 'repository', flags: '--repository <owner/name>', description: 'Alias for --repo.', kind: 'string' },
				{ name: 'workflow', flags: '--workflow <file>', description: 'Workflow file name or path, such as release-gate.yml.', kind: 'string' },
				{ name: 'branch', flags: '--branch <ref>', description: 'Branch or ref to dispatch. Defaults to staging.', kind: 'string' },
				{ name: 'ref', flags: '--ref <ref>', description: 'Alias for --branch.', kind: 'string' },
				{ name: 'input', flags: '--input <key=value>', description: 'workflow_dispatch input. Repeat for multiple inputs.', kind: 'string', repeatable: true },
				{ name: 'plan', flags: '--plan', description: 'Observe and plan without dispatching. This is the default when --execute is omitted.', kind: 'boolean' },
				{ name: 'execute', flags: '--execute', description: 'Dispatch the workflow. Without this flag, only plan and observe.', kind: 'boolean' },
				{ name: 'wait', flags: '--wait', description: 'Wait for the dispatched run to finish. Defaults to on when --execute is used.', kind: 'boolean' },
				{ name: 'timeout', flags: '--timeout <seconds>', description: 'Wait timeout in seconds when --wait is active.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable output.', kind: 'boolean' },
			],
			examples: [
				'treeseed workflow dispatch --repo treeseed-ai/agent --workflow release-gate.yml --branch staging --plan --json',
				'treeseed workflow dispatch --repo treeseed-ai/agent --workflow release-gate.yml --branch staging --execute --json',
			],
			help: {
				longSummary: ['Workflow dispatch is a generic reconciler-backed way to run workflow_dispatch workflows without creating a new commit or push. It uses the same GitHub credential routing and adapter lifecycle as package image publication.'],
				whenToUse: ['Use this to test release-gate workflows or no-op diagnostic workflows from the CLI when a push-triggered run is unnecessary.'],
				beforeYouRun: ['Make sure the selected repository has a Treeseed repository-scoped GitHub token with Actions write permission when dispatching outside the root repository. Plan mode is safe and reports credential blockers.'],
				automationNotes: ['Without --execute this command only refreshes and plans. With --execute it dispatches through github-workflow-dispatch and waits by default so failures are visible in the command result.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'workflow',
		},
	{
			id: 'workspace.package',
			name: 'package',
			aliases: [],
			group: 'Utilities',
			summary: 'Run manifest-driven package workflow planning.',
			description: 'Validate package manifests and plan deployment source/image behavior declared by treeseed.package.yaml.',
			provider: 'default',
			related: ['config', 'hosting', 'db'],
			usage: 'treeseed package [validate|artifact build|artifact verify|artifact hydrate|image|workflow sync] [--package <package-id>]',
			arguments: [{ name: 'action', description: 'Package workflow action.', required: false }],
			options: [
				{ name: 'package', flags: '--package <package-id>', description: 'Discovered package id from treeseed.package.yaml, such as treedx.', kind: 'string' },
				{ name: 'packageRoot', flags: '--package-root <path>', description: 'Package checkout used to build an immutable artifact.', kind: 'string' },
				{ name: 'output', flags: '--output <path>', description: 'Directory for package tarball and integrity manifest output.', kind: 'string' },
				{ name: 'manifest', flags: '--manifest <path>', description: 'Package artifact integrity manifest to verify.', kind: 'string' },
				{ name: 'artifact', flags: '--artifact <path>', description: 'Optional tarball path overriding the manifest-relative artifact.', kind: 'string' },
				{ name: 'artifactsRoot', flags: '--artifacts-root <path>', description: 'Directory containing candidate package artifact manifests.', kind: 'string' },
				{ name: 'projectRoot', flags: '--project-root <path>', description: 'Project whose installed package graph receives candidate artifacts.', kind: 'string' },
				{ name: 'branch', flags: '--branch <branch>', description: 'Package repository branch/ref for source-build planning. Defaults to staging.', kind: 'string' },
				{ name: 'workflow', flags: '--workflow <file>', description: 'GitHub Actions workflow file for package image publication. Defaults to the package manifest.', kind: 'string' },
				{ name: 'syncConfig', flags: '--sync-config', description: 'Sync package image credentials from Treeseed config into the package GitHub environment.', kind: 'boolean' },
				{ name: 'plan', flags: '--plan', description: 'Print the package image plan without dispatching GitHub Actions.', kind: 'boolean' },
				{ name: 'execute', flags: '--execute', description: 'Dispatch a production image workflow when the package policy allows image publication.', kind: 'boolean' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: [
				'treeseed package validate --json',
				'treeseed package artifact build --output .treeseed/artifacts/package --json',
				'treeseed package artifact verify --manifest .treeseed/artifacts/package/manifest.json --json',
				'treeseed package artifact hydrate --artifacts-root .treeseed/artifacts/packages --project-root . --json',
				'treeseed package workflow sync --package all --plan --json',
				'treeseed package image --package treedx --branch staging --plan --json',
				'treeseed package image --package treedx --branch main --plan --json',
			],
			help: {
				longSummary: ['Package workflows are driven by package-local metadata instead of bespoke CLI logic. A checked-out package can declare its repository, production image workflow, hosting source mode, and credential requirements in treeseed.package.yaml.'],
				whenToUse: ['Use this to validate source-build staging behavior or production semantic image publication for packages such as TreeDX.'],
				beforeYouRun: ['Run `trsd config` to configure repository-scoped GitHub credentials and provider secrets. Do not pass package repository tokens or Docker Hub secrets on the command line.'],
				automationNotes: ['Use `--json` to capture selected package metadata, repository credential routing, source-build readiness, Docker Hub readiness for production, and the hosting override command.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'package',
		},
];
