import { TREESEED_DEFAULT_STARTER_TEMPLATE_ID } from '@treeseed/sdk';
import {
	command, detail, devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS, type CommandOverlay,
} from './operations-registry-support.ts';

export const CLI_COMMAND_OVERLAYS_3: Array<[string, CommandOverlay]> = [
	['config', command({
		options: [
			{ name: 'full', flags: '--full', description: 'Open the advanced full editor directly in human interactive mode.', kind: 'boolean' },
			{ name: 'mouse', flags: '--mouse', description: 'Opt into mouse capture for the config UI. Keyboard-first terminal behavior remains the default.', kind: 'boolean' },
			{ name: 'environment', flags: '--environment <scope>', description: 'Select all environments or limit configuration to local, staging, or prod. Defaults to all.', kind: 'enum', repeatable: true, values: ['all', 'local', 'staging', 'prod'] },
			{ name: 'sync', flags: '--sync <mode>', description: 'Sync hosted secrets/variables to GitHub, Cloudflare, Railway, or all providers. Defaults to all; GitHub binding changes are applied through reconciler-owned units.', kind: 'enum', values: ['none', 'github', 'cloudflare', 'railway', 'all'] },
			{ name: 'bootstrap', flags: '--bootstrap', description: 'Skip the editor and run platform reconciliation/bootstrap from the currently saved required values.', kind: 'boolean' },
			{ name: 'system', flags: '--system <system>', description: 'Limit bootstrap to a system group. Repeatable. Values: all, github, data, web, api, agents.', kind: 'enum', repeatable: true, values: ['all', 'github', 'data', 'web', 'api', 'agents'] },
			{ name: 'systems', flags: '--systems <systems>', description: 'Comma-separated bootstrap system groups. Values: all, github, data, web, api, agents.', kind: 'string' },
			{ name: 'skipUnavailable', flags: '--skip-unavailable', description: 'Skip selected bootstrap systems whose required provider credentials are not configured.', kind: 'boolean' },
			{ name: 'bootstrapSequential', flags: '--bootstrap-sequential', description: 'Run bootstrap DAG tasks sequentially for ordered debugging logs.', kind: 'boolean' },
			{ name: 'preflight', flags: '--preflight', description: 'Inspect bootstrap verification readiness and planned checks without mutating provider resources.', kind: 'boolean' },
			{ name: 'nonInteractive', flags: '--non-interactive', description: 'Apply resolved values without opening the interactive UI. Required for non-TTY automation unless using an operational mode such as --print-env-only.', kind: 'boolean' },
			{ name: 'installMissingTooling', flags: '--install-missing-tooling', description: 'Install missing config verification tooling such as `gh-act` during the run instead of only reporting it.', kind: 'boolean' },
			{ name: 'printEnv', flags: '--print-env', description: 'Print resolved environment values before remote initialization.', kind: 'boolean' },
			{ name: 'printEnvOnly', flags: '--print-env-only', description: 'Print resolved environment values, check provider connections, and exit without prompting or initializing remote resources.', kind: 'boolean' },
			{ name: 'showSecrets', flags: '--show-secrets', description: 'Print full secret values in environment reports instead of masking them.', kind: 'boolean' },
			{ name: 'rotateMachineKey', flags: '--rotate-machine-key', description: 'Regenerate the local home machine key and re-encrypt stored Treeseed secrets and remote auth sessions.', kind: 'boolean' },
			{ name: 'connectMarket', flags: '--connect-market', description: 'Pair the current local repo to a TreeSeed project and register the hybrid runner connection.', kind: 'boolean' },
			{ name: 'marketBaseUrl', flags: '--market-base-url <url>', description: 'TreeSeed control-plane base URL for --connect-market. Defaults to the active remote host.', kind: 'string' },
			{ name: 'marketTeamId', flags: '--market-team-id <id>', description: 'Team ID to record in the local TreeSeed pairing metadata.', kind: 'string' },
			{ name: 'marketTeamSlug', flags: '--market-team-slug <slug>', description: 'Team slug to record in the local TreeSeed pairing metadata.', kind: 'string' },
			{ name: 'marketProjectId', flags: '--market-project-id <id>', description: 'Project ID to pair with when using --connect-market.', kind: 'string' },
			{ name: 'marketProjectSlug', flags: '--market-project-slug <slug>', description: 'Project slug to record in the local TreeSeed pairing metadata.', kind: 'string' },
			{ name: 'marketProjectApiBaseUrl', flags: '--market-project-api-base-url <url>', description: 'Override the project API base URL recorded on the TreeSeed project connection.', kind: 'string' },
			{ name: 'marketAccessToken', flags: '--market-access-token <token>', description: 'Explicit TreeSeed access token to use for pairing. Prefer an existing remote session when possible.', kind: 'string' },
			{ name: 'rotateRunnerToken', flags: '--rotate-runner-token', description: 'Rotate the project runner credential while pairing the local hybrid repo.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed config', 'treeseed config --full --mouse', 'treeseed config --environment all', 'treeseed config --environment staging --bootstrap', 'treeseed config --environment staging --bootstrap --system web', 'treeseed config --environment staging --bootstrap --preflight', 'treeseed config --environment local --sync none', 'treeseed config --environment local --sync none --non-interactive', 'treeseed config --environment staging --print-env-only --show-secrets', 'treeseed config --rotate-machine-key', 'treeseed config --connect-market --market-project-id kc_proj_123'],
		notes: ['Does not create branch preview deployments. Use `treeseed switch <branch> --preview` for that.'],
		help: {
			workflowPosition: 'configure runtime',
			longSummary: [
				'Config is the runtime foundation command for Treeseed. It resolves local and hosted environment values, captures missing values, runs the startup wizard or full editor for human use, and can synchronize provider-backed secrets and variables.',
				'Use it whenever environment configuration, provider auth, shared defaults, or machine-local secret state need to be inspected or updated.',
			],
			whenToUse: [
				'Use this during first-run setup, after new required environment variables are introduced, or when provider-backed configuration drift must be repaired.',
				'Use the startup wizard for onboarding and the full editor when you need complete per-variable control. Terminal-native copy, selection, and paste are the default interaction model.',
			],
			beforeYouRun: [
				'Decide whether you want human interactive mode, explicit `--non-interactive` application, or machine-readable `--json` output before invoking the command.',
				'Choose the environment scope you care about: all, local, staging, or prod.',
				'If you plan to sync hosted state, make sure GitHub, Cloudflare, and Railway authentication is already configured or be ready to log in first.',
			],
			outcomes: [
				'Collects current, suggested, shared, and scoped environment values.',
				'Allows interactive editing for humans or structured application for automation.',
				'Optionally synchronizes hosted provider state and rotates the local machine key.',
			],
			examples: [
				example('treeseed config', 'Run the startup wizard', 'Open the newcomer-friendly configuration wizard in human TTY mode.'),
				example('treeseed config --full', 'Open the advanced editor directly', 'Skip the startup wizard and go straight to the full configuration surface.'),
				example('treeseed config --full --mouse', 'Opt into mouse capture for the editor', 'Keep the keyboard-first defaults unless you explicitly want click and wheel interaction inside the config UI.'),
				example('treeseed config --environment staging --bootstrap', 'Bootstrap infrastructure from saved config', 'Skip the editor and run reconciliation/bootstrap when the required values are already configured.'),
				example('treeseed config --environment staging --bootstrap --system web', 'Bootstrap only the hosted hub', 'Provision data and web systems while leaving optional API and agent Railway services alone.'),
				example('treeseed config --environment staging --bootstrap --preflight', 'Inspect bootstrap verification readiness', 'Show the resolved units, verification capabilities, and planned reconcile actions without mutating provider resources.'),
				example('treeseed config --environment local --sync none', 'Edit local values without provider sync', 'Limit the session to local values and avoid hosted synchronization while iterating locally.'),
				example('treeseed config --environment local --sync none --non-interactive', 'Apply deterministic local config in automation', 'Use the resolved current and suggested values without opening the interactive UI.'),
				example('treeseed config --environment staging --print-env-only --show-secrets', 'Inspect a resolved environment report', 'Print the resolved staging environment with full secret visibility and exit.'),
				example('treeseed config --rotate-machine-key', 'Rotate the local secret encryption key', 'Regenerate the machine key and re-encrypt locally stored Treeseed secrets.'),
				example('treeseed config --connect-market --market-project-id kc_proj_123', 'Pair a hybrid repo to TreeSeed', 'Register the current local repo as the hybrid runner connection for an existing TreeSeed project.'),
			],
			optionDetails: [
				detail('--full', 'Enter the advanced editor directly instead of the startup wizard.'),
				detail('--mouse', 'Opt into terminal mouse capture for clicking, scrolling, and focus changes inside the config UI.'),
				detail('--environment <scope>', 'Filter configuration to `all`, `local`, `staging`, or `prod`.'),
				detail('--sync <mode>', 'Choose which provider surfaces should receive synchronized values after local updates are applied.'),
				detail('--bootstrap', 'Skip the editor and run the reconcile/bootstrap path from the values already stored in machine config.'),
				detail('--system <system>', 'Limit bootstrap to a stable system group. Repeat it to select multiple groups.'),
				detail('--systems <systems>', 'Comma-separated form of --system for automation.'),
				detail('--skip-unavailable', 'Skip selected systems whose provider credentials are missing instead of failing the run.'),
				detail('--bootstrap-sequential', 'Run bootstrap DAG tasks one at a time to preserve log order for debugging or LLM review.'),
				detail('--preflight', 'When combined with `--bootstrap`, inspect verification readiness and planned reconcile actions without mutating provider resources.'),
				detail('--non-interactive', 'Apply resolved values without opening the interactive editor. Use this for automation when you do not want `--json` output.'),
				detail('--install-missing-tooling', 'Allow config to install missing verification helpers such as the GitHub `gh-act` extension instead of only reporting them.'),
				detail('--print-env', 'Print the resolved environment values before remote initialization continues.'),
				detail('--print-env-only', 'Print the environment report and exit without interactive editing or remote initialization.'),
				detail('--rotate-machine-key', 'Rotate the local machine key used for encrypted Treeseed secret storage.'),
				detail('--connect-market', 'Pair the current repo to a TreeSeed project and store the resulting market connection metadata locally.'),
			],
			automationNotes: [
				'Use `--json` for machine-readable automation, or `--non-interactive` when you want deterministic application without interactive UI.',
				'`--bootstrap`, `--bootstrap --preflight`, `--print-env-only`, `--rotate-machine-key`, and `--connect-market` are operational paths that bypass the interactive UI.',
				'Config reports missing tooling by default. Use `--install-missing-tooling` when you want the command to attempt installation.',
				'Shared versus scoped environment semantics are resolved inside the SDK; the CLI help should be treated as the operator-facing explanation layer.',
			],
			warnings: [
				'This command does not create branch preview deployments. Use `switch --preview` for task-preview lifecycle work.',
				'When `--show-secrets` is enabled, output is intentionally unmasked. Avoid using it in logs or shared terminals unless that disclosure is acceptable.',
			],
			relatedDetails: [
				related('doctor', 'Use `doctor` when the problem is diagnostic uncertainty rather than direct environment editing.'),
				related('auth:login', 'Use `auth:login` when provider-backed operations fail because the CLI is not authenticated.'),
				related('switch', 'Use `switch --preview` for branch preview lifecycle work, which is intentionally separate from config.'),
			],
		},
		executionMode: 'handler',
		handlerName: 'config',
	})],
	['export', command({
		arguments: [{ name: 'directory', description: 'Directory subtree to export. Defaults to the current shell directory.', required: false }],
		options: [
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed export', 'treeseed export src', 'treeseed export packages/sdk --json'],
		help: {
			workflowPosition: 'package codebase',
			longSummary: [
				'Export generates a Markdown codebase snapshot for the selected directory using the SDK-owned Repomix integration. It is designed for AI context bundling and archival of the current project tree.',
			],
			whenToUse: [
				'Use this when you need a portable Markdown snapshot of a project subtree for AI context, review, or archival.',
				'Use the positional directory when you want to export a subtree instead of the current shell directory.',
			],
			beforeYouRun: [
				'Run from somewhere inside the Treeseed project you want to export, or pass the exact subtree explicitly.',
				'Remember that `.treeseed/exports` is always ignored so exports do not recursively contain older exports.',
			],
			outcomes: [
				'Writes a Markdown package under `.treeseed/exports` relative to the exported directory.',
				'Reports branch, timestamp, ignore patterns, and summary metadata.',
			],
			examples: [
				example('treeseed export', 'Export from the current shell directory', 'Generate a codebase snapshot rooted at the directory you are currently in.'),
				example('treeseed export src', 'Export a source subtree', 'Limit the snapshot to the `src` subtree relative to the current workspace.'),
				example('treeseed export packages/sdk --json', 'Use export in automation', 'Emit structured metadata about the generated Markdown snapshot.'),
			],
			warnings: [
				'The export output directory is always relative to the directory being exported, not necessarily the tenant root.',
			],
			relatedDetails: [
				related('config', 'Use `config` when you need runtime configuration context rather than a code snapshot.'),
				related('status', 'Use `status` to understand workflow state before capturing a code export for external analysis.'),
			],
		},
		executionMode: 'handler',
		handlerName: 'export',
	})],
	['release', command({
		usage: 'treeseed release --major|--minor|--patch|--repair-version-line',
		options: [
			{ name: 'major', flags: '--major', description: 'Bump to the next major version.', kind: 'boolean' },
			{ name: 'minor', flags: '--minor', description: 'Bump to the next minor version.', kind: 'boolean' },
			{ name: 'patch', flags: '--patch', description: 'Bump to the next patch version.', kind: 'boolean' },
			{ name: 'repairVersionLine', flags: '--repair-version-line', description: 'Repair public package major.minor drift without enforcing patch parity.', kind: 'boolean' },
			{ name: 'targetVersionLine', flags: '--target-version-line <major.minor>', description: 'Target release line for --repair-version-line, for example 0.10.', kind: 'string' },
			{ name: 'ciMode', flags: '--ci <mode>', description: 'Control hosted GitHub Actions waits.', kind: 'enum', values: ['auto', 'hosted', 'off'] },
			{ name: 'workspaceLinks', flags: '--workspace-links <mode>', description: 'Control local workspace package links.', kind: 'enum', values: ['auto', 'off'] },
			{ name: 'verifyDeployedResources', flags: '--verify-deployed-resources', description: 'Force production deployment checks to verify provider resources before release returns.', kind: 'boolean' },
			{ name: 'fresh', flags: '--fresh', description: 'Start a new release instead of auto-resuming stale failed release runs.', kind: 'boolean' },
			{ name: 'sceneArtifacts', flags: '--scene-artifacts <mode>', description: 'Choose scene evidence mode for release guarantees.', kind: 'enum', values: ['full', 'screenshots'] },
			{ name: 'noSceneVideo', flags: '--no-scene-video', description: 'Alias for --scene-artifacts screenshots.', kind: 'boolean' },
			{ name: 'plan', flags: '--plan', description: 'Compute the recursive release plan without mutating any repo.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed release --patch', 'treeseed release --minor --verify-deployed-resources', 'treeseed release --repair-version-line --target-version-line 0.10 --plan', 'treeseed release --patch --fresh'],
		notes: ['Requires exactly one bump flag unless --repair-version-line is used.'],
		help: {
			workflowPosition: 'promote to production',
			longSummary: [
				'Release promotes the staging state to production while applying a version bump. It is the forward promotion command once staging reflects the exact state you intend to publish.',
			],
			whenToUse: [
				'Use this only when staging is the approved source for production promotion.',
				'Choose exactly one bump flag so the release version reflects the intended change size, or use --repair-version-line to repair package line drift.',
				'Use `--verify-deployed-resources` when production provider resources must be checked before the release returns.',
			],
			beforeYouRun: [
				'Confirm staging is in the state you want to promote.',
				'Run `treeseed release-candidate --strict` first if you want to inspect the full proof before release; release will require strict proof for the exact staging state.',
				'Choose one of `--major`, `--minor`, `--patch`, or `--repair-version-line` before running the command.',
			],
			outcomes: [
				'Promotes the release forward and records the version bump.',
				'Returns release metadata in JSON mode when requested.',
			],
			examples: [
				example('treeseed release --patch', 'Patch release', 'Promote staging to production with the next patch version.'),
				example('treeseed release --minor --verify-deployed-resources', 'Minor release with hosted checks', 'Promote staging with the next minor version bump and verify production provider resources.'),
				example('treeseed release --repair-version-line --target-version-line 0.10 --json', 'Repair package line drift', 'Publish only packages below the selected public package release line.'),
				example('treeseed release --patch --json', 'Automate release tracking', 'Emit structured release output for tooling that records deployments and version changes.'),
			],
			warnings: [
				'Exactly one bump flag is required unless --repair-version-line is used.',
				'This is a production-facing promotion command, not a dry local build operation.',
			],
			relatedDetails: [
				related('stage', 'Use `stage` first to move completed task work into staging before releasing.'),
				related('rollback', 'Use `rollback` when a staging or production deployment must be restored to an earlier state.'),
			],
		},
		executionMode: 'handler',
		handlerName: 'release',
	})],
	['destroy', command({
		usage: 'treeseed destroy --environment <local|staging|prod> [--plan] [--delete-data] [--sweep-treeseed] [--force] [--skip-confirmation] [--confirm <slug>] [--remove-build-artifacts]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Select the persistent environment to destroy.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'plan', flags: '--plan', description: 'Compute the destroy plan without mutating the environment.', kind: 'boolean' },
			{ name: 'deleteData', flags: '--delete-data', description: 'Also delete data repositories such as PostgreSQL, D1, and R2 for the target environment.', kind: 'boolean' },
			{ name: 'sweepTreeseed', flags: '--sweep-treeseed', description: 'Sweep all TreeSeed-owned Cloudflare and Railway resources across persistent environments. Requires careful provider verification.', kind: 'boolean' },
			{ name: 'force', flags: '--force', description: 'Force worker deletion when supported.', kind: 'boolean' },
			{ name: 'skipConfirmation', flags: '--skip-confirmation', description: 'Skip the interactive confirmation prompt.', kind: 'boolean' },
			{ name: 'confirm', flags: '--confirm <slug>', description: 'Provide the expected slug confirmation non-interactively.', kind: 'string' },
			{ name: 'removeBuildArtifacts', flags: '--remove-build-artifacts', description: 'Also remove local build artifacts after destroy.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed destroy --environment staging --delete-data --plan', 'treeseed destroy --environment staging --delete-data --sweep-treeseed --force --confirm example --skip-confirmation'],
		notes: ['Only for persistent environments. Task cleanup belongs to treeseed close.', 'This command is destructive and requires explicit confirmation.'],
		help: {
			workflowPosition: 'tear down environment',
			longSummary: [
				'Destroy tears down a persistent environment and, optionally, related local build artifacts. It is the destructive environment cleanup command and should be treated as an explicit operator workflow.',
			],
			whenToUse: [
				'Use this when a persistent environment should be intentionally removed rather than rolled back or updated.',
				'Use `--plan` first when you want to inspect the destroy plan without committing to it.',
				'Use `--delete-data` only when PostgreSQL, D1, and R2 data repositories should be removed instead of preserved.',
			],
			beforeYouRun: [
				'Confirm the environment scope exactly. This command does not target task-branch cleanup; it targets persistent environments only.',
				'Plan your confirmation strategy: interactive prompt, `--skip-confirmation`, or explicit `--confirm <slug>`.',
			],
			outcomes: [
				'Destroys the selected persistent environment resources according to provider support.',
				'Optionally removes local build artifacts if requested.',
			],
			examples: [
				example('treeseed destroy --environment staging --delete-data --plan', 'Preview the full destroy plan', 'Inspect what would be removed from staging, including data repositories, without actually performing the destroy.'),
				example('treeseed destroy --environment prod --delete-data --confirm example --skip-confirmation', 'Run a deliberate non-interactive destroy', 'Provide the expected slug explicitly when operating in a scripted or no-prompt environment.'),
				example('treeseed destroy --environment local --delete-data --remove-build-artifacts', 'Remove a local environment and its artifacts', 'Destroy the local environment and also delete local runtime data and build outputs.'),
			],
			warnings: [
				'This command is destructive.',
				'Persistent environment destroy is not the same thing as task cleanup. Use `close` for task-branch archival.',
			],
			relatedDetails: [
				related('rollback', 'Use `rollback` when the environment should remain but move back to an earlier deployment.'),
				related('close', 'Use `close` when the thing you want to clean up is a task branch, not a persistent environment.'),
			],
		},
		executionMode: 'handler',
		handlerName: 'destroy',
	})],
	['dev', command({
		options: DEV_RUNTIME_OPTIONS,
		arguments: [{ name: 'subcommand', description: 'Optional managed instance action: start, status, logs, stop, or restart.', required: false }],
		examples: ['treeseed dev', 'treeseed dev start', 'treeseed dev status --all --json', 'treeseed dev logs', 'treeseed dev stop', 'treeseed dev --web-runtime local --plan --json'],
		help: {
			longSummary: [
				'Dev starts or manages the local Treeseed Market web/API/runtime services.',
				'Without a subcommand, dev runs as the existing foreground supervisor.',
				'Capacity provider lifecycle is package-owned and runs through `treeseed capacity ...`, not through `treeseed dev`.',
			],
			beforeYouRun: [
				'Run from the tenant or workspace root you want to develop.',
				'From the Market repo root, dev automatically starts the local API, managed local PostgreSQL, and Treeseed operations runner alongside the web UI.',
				'Use `dev start` for worktree-scoped background instance management that AI agents can discover and stop later.',
				'Use `--plan --json` when you want to inspect fixed web/API/runner commands, setup steps, readiness checks, watched paths, and restart policy without starting services.',
				'Use `--reset` when you want a fresh local D1 database, Treeseed PostgreSQL state, Mailpit inbox, generated worker bundle, and Wrangler temp output without deleting configuration.',
				'Dev prints the local web URL after readiness; it does not open a browser unless you pass `--open on` or `--open auto`.',
				'Keep the foreground process running while you test. Press Ctrl+C to stop the supervised stack and free the local ports.',
			],
			examples: [
				example('treeseed dev', 'Start local Market development', 'Run web, API, managed PostgreSQL setup, and the Treeseed operations runner locally.'),
				example('treeseed dev start', 'Start a managed worktree instance', 'Launch the same dev runtime detached, write worktree-local PID/log/state files, and return after readiness.'),
				example('treeseed dev status --all --json', 'Inspect all worktree instances', 'List managed dev instances discovered through the repository-family index.'),
				example('treeseed dev logs', 'Show managed dev logs', 'Print the current worktree managed dev log file.'),
				example('treeseed dev stop', 'Stop managed dev', 'Stop only the current worktree managed dev instance.'),
				example('treeseed dev --reset', 'Start from a fresh local runtime', 'Clear disposable local dev state, rerun setup and database migrations, then start the dev supervisor.'),
				example('treeseed dev --reset --plan --json', 'Inspect reset actions', 'Emit the reset, setup, readiness, command, and watch plan without deleting local state or starting services.'),
				example('treeseed dev --plan --json', 'Inspect the runtime plan', 'Emit a structured plan with setup steps, commands, ports, URLs, readiness checks, and watch entries.'),
				example('treeseed dev --web-runtime local --plan --json', 'Inspect local web runtime', 'Plan fixed web/API/runner startup using the local Astro web runtime.'),
				example('treeseed dev --port 4322', 'Change the web port', 'Start the fixed web/API/runner runtime with the Astro UI on a specific port.'),
				example('treeseed dev --open on', 'Open the browser explicitly', 'Start the integrated runtime and launch the local web URL after readiness.'),
				example('trsd dev', 'Use the short alias', 'Start the same local runtime through the shorter entrypoint.'),
				example('treeseed dev --json', 'Stream dev events', 'Emit newline-delimited events while the long-running dev process supervises local services.'),
			],
			outcomes: [
				'Starts fixed local web/API/runner surfaces, waits for readiness, prints the local URL, and then remains attached as the live supervisor.',
				'Restarts required crashed surfaces with capped exponential backoff and keeps setup/readiness failures alive for retry.',
				'Stops watchers first and then terminates service process groups when the foreground command exits.',
			],
		},
		executionMode: 'handler',
		handlerName: 'dev',
	})],
];
