import type { TreeseedOperationSpec } from './operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from './operations-registry-support.ts';

export const CLI_ONLY_OPERATION_SPECS_3: TreeseedOperationSpec[] = [
	{
		id: 'market.capacity',
		name: 'capacity',
		aliases: [],
		group: 'Utilities',
		summary: 'Inspect capacity diagnostics and operate the package-owned capacity provider runtime.',
		description: 'Govern provider memberships, grants, allocations, workdays, assignments, and package-owned provider lifecycle resources.',
		provider: 'default',
		related: ['teams', 'projects', 'agents'],
		usage: 'treeseed capacity <governance|provider|workday|runtime action> [options] [--json]',
		arguments: [{ name: 'action', description: 'Capacity action.', required: false }],
		options: [
			{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
			{ name: 'provider', flags: '--provider <provider-id>', description: 'Provider id or local provider selector for diagnostics.', kind: 'string' },
			{ name: 'connection', flags: '--connection <connection-id>', description: 'Connection id from the capacity provider manifest.', kind: 'string' },
			{ name: 'displayName', flags: '--display-name <name>', description: 'Provider identity display name used when initializing a manifest.', kind: 'string' },
			{ name: 'providerMarketUrl', flags: '--provider-market-url <url>', description: 'Market API URL written into a new provider connection.', kind: 'string' },
			{ name: 'providerMarketProfile', flags: '--provider-market-profile <profile>', description: 'Portable Market profile written into a new provider connection.', kind: 'string' },
			{ name: 'registrationKeyRef', flags: '--registration-key-ref <secret-ref>', description: 'One-time provider-join secret reference for the team broadcast registration key; never persisted in the provider manifest.', kind: 'string' },
			{ name: 'identityKeyRef', flags: '--identity-key-ref <secret-ref>', description: 'Secret reference for the provider Ed25519 private identity.', kind: 'string' },
			{ name: 'team', flags: '--team <team-id>', description: 'Team id for Market capacity migration or coordination-record inspection.', kind: 'string' },
			{ name: 'request', flags: '--request <request-id>', description: 'Provider registration request id.', kind: 'string' },
			{ name: 'membership', flags: '--membership <membership-id>', description: 'Approved provider/team membership id.', kind: 'string' },
			{ name: 'credential', flags: '--credential <credential-id>', description: 'Membership credential id.', kind: 'string' },
			{ name: 'grant', flags: '--grant <grant-id>', description: 'Capacity grant id.', kind: 'string' },
			{ name: 'allocation', flags: '--allocation <allocation-id>', description: 'Capacity allocation-set id.', kind: 'string' },
			{ name: 'agentClass', flags: '--agent-class <class-id>', description: 'Project agent-class id for inspection.', kind: 'string' },
			{ name: 'availableCredits', flags: '--available-credits <credits>', description: 'Positive workday credit budget.', kind: 'string' },
			{ name: 'idempotencyKey', flags: '--idempotency-key <key>', description: 'Stable mutation idempotency key.', kind: 'string' },
			{ name: 'yes', flags: '--yes', description: 'Confirm registration-key reveal or rotation for noninteractive automation.', kind: 'boolean' },
			{ name: 'teamAlias', flags: '--team-alias <alias>', description: 'Optional team-local provider alias assigned during approval.', kind: 'string' },
			{ name: 'reason', flags: '--reason <reason>', description: 'Governance decision or lifecycle reason.', kind: 'string' },
			{ name: 'auditAction', flags: '--audit-action <action>', description: 'Filter durable capacity audit events by exact action.', kind: 'string' },
			{ name: 'resourceType', flags: '--resource-type <type>', description: 'Filter durable capacity audit events by resource type.', kind: 'string' },
			{ name: 'resourceId', flags: '--resource-id <id>', description: 'Filter durable capacity audit events by resource id.', kind: 'string' },
			{ name: 'file', flags: '--file <path>', description: 'YAML or JSON capacity policy document.', kind: 'string' },
			{ name: 'document', flags: '--document <yaml-or-json>', description: 'Inline YAML or JSON capacity policy document.', kind: 'string' },
			{ name: 'capabilities', flags: '--capabilities <csv>', description: 'Allowed provider capabilities for a grant.', kind: 'string' },
			{ name: 'modes', flags: '--modes <csv>', description: 'Allowed assignment modes for a grant.', kind: 'string' },
			{ name: 'executionProviders', flags: '--execution-providers <csv>', description: 'Allowed execution-provider ids for a grant.', kind: 'string' },
			{ name: 'dailyCredits', flags: '--daily-credits <amount>', description: 'Daily governed credit limit.', kind: 'string' },
			{ name: 'monthlyCredits', flags: '--monthly-credits <amount>', description: 'Monthly governed credit limit.', kind: 'string' },
			{ name: 'maxConcurrentAssignments', flags: '--max-concurrent-assignments <count>', description: 'Maximum concurrent assignments for a grant.', kind: 'string' },
			{ name: 'unmetered', flags: '--unmetered', description: 'Explicitly mark a grant as unmetered.', kind: 'boolean' },
			{ name: 'expiresAt', flags: '--expires-at <timestamp>', description: 'Optional grant expiry timestamp.', kind: 'string' },
			{ name: 'project', flags: '--project <project-id>', description: 'Project id for Market capacity diagnostics, allocation migration, agent-class inspection, assignment filtering, or mode-run inspection.', kind: 'string' },
			{ name: 'status', flags: '--status <status>', description: 'Filter provider sessions or assignments by durable lifecycle status.', kind: 'string' },
			{ name: 'mode', flags: '--mode <planning|acting>', description: 'Filter project mode-run inspection by kernel mode.', kind: 'string' },
			{ name: 'assignment', flags: '--assignment <assignment-id>', description: 'Filter assignment, mode-run, execution-run, or audit inspection by exact provider assignment id.', kind: 'string' },
			{ name: 'reservation', flags: '--reservation <reservation-id>', description: 'Reservation id for inspection, explanation, or overrun approval decisions.', kind: 'string' },
			{ name: 'decision', flags: '--decision <decision-id>', description: 'Decision id for planning readiness and execution input inspection.', kind: 'string' },
			{ name: 'workday', flags: '--workday <workday-id>', description: 'Workday id for capacity envelope and settlement summary inspection.', kind: 'string' },
			{ name: 'projects', flags: '--projects <all|csv>', description: 'Project slug selector for portfolio workdays.', kind: 'string' },
			{ name: 'seed', flags: '--seed <profile>', description: 'Seed profile to verify before scheduling an API-owned workday.', kind: 'string' },
			{ name: 'purpose', flags: '--purpose <text>', description: 'Human purpose label for the workday run.', kind: 'string' },
			{ name: 'workdays', flags: '--workdays <count>', description: 'Number of coordinated workdays to schedule.', kind: 'string' },
			{ name: 'durationSeconds', flags: '--duration-seconds <seconds>', description: 'Minimum duration for the live workday before settlement and scoring.', kind: 'string' },
			{ name: 'maxActiveAssignments', flags: '--max-active-assignments <count>', description: 'Maximum active API-synthesized assignments to keep queued while the timed workday is open.', kind: 'string' },
			{ name: 'planningOnly', flags: '--planning-only', description: 'Limit workday expectations to planning mode.', kind: 'boolean' },
			{ name: 'acting', flags: '--acting', description: 'Allow acting-capable output expectations when approved decisions exist.', kind: 'boolean' },
			{ name: 'abort', flags: '--abort', description: 'Abort a live workday when degradation or failed assignment evidence appears.', kind: 'boolean' },
			{ name: 'reportDir', flags: '--report-dir <path>', description: 'Directory for generated workday JSON and Markdown reports.', kind: 'string' },
			{ name: 'environment', flags: '--environment <scope>', description: 'Treeseed config scope used when resolving encrypted provider launch values.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'kind', flags: '--kind <provider-kind>', description: 'Execution provider kind such as codex or openrouter.', kind: 'string' },
			{ name: 'executionProvider', flags: '--execution-provider <id>', description: 'Filter execution-run audit output to one native execution provider id.', kind: 'string' },
			{ name: 'format', flags: '--format <text|yaml|timeline|tree|json>', description: 'Render selected inspection commands as text, YAML, timeline, tree, or JSON.', kind: 'string' },
			{ name: 'limit', flags: '--limit <count>', description: 'Maximum records to return from a bounded capacity inspection page.', kind: 'string' },
			{ name: 'cursor', flags: '--cursor <cursor>', description: 'Opaque cursor for the next capacity governance collection page.', kind: 'string' },
			{ name: 'evidence', flags: '--evidence <collection>', description: 'Select a paginated workday evidence collection: assignments, mode-runs, reservations, usage-actuals, or ledger-entries.', kind: 'enum', values: ['assignments', 'mode-runs', 'reservations', 'usage-actuals', 'ledger-entries'] },
			{ name: 'dataDir', flags: '--data-dir <path>', description: 'Host data directory mounted into the provider container at /data.', kind: 'string' },
			{ name: 'waitSeconds', flags: '--wait-seconds <seconds>', description: 'Seconds to wait for provider settlement after the timed workday duration.', kind: 'string' },
			{ name: 'mouse', flags: '--mouse', description: 'Opt into mouse capture for interactive forensic workday-log views when available.', kind: 'boolean' },
			{ name: 'config', flags: '--config <path>', description: 'Capacity provider launch manifest path.', kind: 'string' },
			{ name: 'agentPackageRoot', flags: '--agent-package-root <path>', description: 'Path to a built @treeseed/agent package root.', kind: 'string' },
			{ name: 'diagnostic', flags: '--diagnostic', description: 'Start lifecycle commands without live Market registration or provider credentials.', kind: 'boolean' },
			{ name: 'plan', flags: '--plan', description: 'Render the selected capacity-provider reconcile plan without mutating local Docker or provider state.', kind: 'boolean' },
			{ name: 'execute', flags: '--execute', description: 'Apply the selected capacity-provider reconcile resources.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: [
			'treeseed capacity doctor --market local --provider local',
			'treeseed capacity diagnostics --market local --project project_123 --environment local',
			'treeseed capacity register --market local --provider local --json',
			'treeseed capacity plan --market local --provider local --json',
			'treeseed capacity allocation-sets --market local --team team_123 --json',
			'treeseed capacity grant-validate --market local --team team_123 --file capacity-grant.yaml --json',
			'treeseed capacity grant-plan --market local --team team_123 --file capacity-grant.yaml --json',
			'treeseed capacity allocation-validate --market local --team team_123 --file capacity-allocation.yaml --json',
			'treeseed capacity allocation-supersede --market local --team team_123 --allocation allocation_2 --document \'{expectedActiveAllocationSetId: allocation_1}\' --execute --json',
			'treeseed capacity allocation-explain --market local --team team_123 --allocation allocation_2 --file admission-request.yaml --json',
			'treeseed capacity registration-key-reveal --market local --team team_123 --yes --json',
			'treeseed capacity registration-key-rotate --market local --team team_123 --execute --yes --json',
			'treeseed capacity agent-classes --market local --project project_123 --json',
			'treeseed capacity agent-class --market local --project project_123 --agent-class class_123 --json',
			'treeseed capacity agent-classes-sync --market local --project project_123 --file agent-classes.yaml --plan --json',
			'treeseed capacity provider-offer-validate --connection primary-team --file provider-offer.yaml --json',
			'treeseed capacity provider-offer-plan --connection primary-team --file provider-offer.yaml --json',
			'treeseed capacity provider-offer-apply --connection primary-team --file provider-offer.yaml --execute --json',
			'treeseed capacity availability-sessions --market local --team team_123 --provider provider_123 --json',
			'treeseed capacity assignments --market local --team team_123 --status leased --json',
			'treeseed capacity assignment --market local --team team_123 --assignment assignment_123 --json',
			'treeseed capacity reservations --market local --team team_123 --project project_123 --limit 50 --json',
			'treeseed capacity reservation-explanation --market local --team team_123 --reservation reservation_123 --json',
			'treeseed capacity usage-export --market local --team team_123 --project project_123 --file .treeseed/exports/usage.json --json',
			'treeseed capacity ledger-export --market local --team team_123 --project project_123 --file .treeseed/exports/ledger.json --json',
			'treeseed capacity audit-events --market local --team team_123 --audit-action assignment-synthesis.denied --json',
			'treeseed capacity audit-export --market local --team team_123 --file .treeseed/exports/capacity-audit.json --json',
			'treeseed capacity mode-runs --market local --project project_123 --mode planning --json',
			'treeseed capacity execution-runs --market local --team treeseed --kind codex --format yaml',
			'treeseed capacity workday-log --market local --team treeseed --workday workday_123 --format tree',
			'treeseed capacity decision-planning --market local --decision decision_123 --json',
			'treeseed capacity execution-inputs --market local --decision decision_123 --json',
			'treeseed capacity capacity-plans --market local --decision decision_123 --json',
			'treeseed capacity capacity-plan --market local --capacity-plan capacity_plan_123 --json',
			'treeseed capacity workday-summary --market local --workday workday_123 --json',
			'treeseed capacity workday-summary --market local --workday workday_123 --evidence ledger-entries --limit 50 --json',
			'treeseed capacity workday-create --market local --project project_123 --available-credits 50 --execute --json',
			'treeseed capacity workday-start --market local --workday workday_123 --execute --json',
			'treeseed capacity workday-tick --market local --team team_123 --workday run_123 --execute --json',
			'treeseed capacity assignment-cancel --market local --team team_123 --assignment assignment_123 --plan --json',
			'treeseed capacity assignment-requeue --market local --team team_123 --assignment assignment_123 --execute --json',
			'treeseed capacity checkpoint-integrate --market local --team team_123 --assignment assignment_123 --plan --json',
			'treeseed capacity overrun-approve --market local --team team_123 --reservation reservation_123 --execute --json',
			'treeseed capacity workday-run --market local --team team_123 --provider local --workdays 1 --duration-seconds 900 --execute --json',
			'treeseed capacity assignment-explanation --market local --team team_123 --assignment assignment_123 --json',
			'treeseed capacity fallback-outputs --market local --project project_123 --json',
			'treeseed capacity treedx-proxy-audit --market local --project project_123 --assignment assignment_123 --json',
			'treeseed capacity build',
			'treeseed capacity up --market local --provider local',
			'treeseed capacity up --config treeseed.capacity-provider.yaml',
			'treeseed capacity up --market local --provider local --diagnostic',
			'treeseed capacity status --market local --provider local',
			'treeseed capacity logs --market local --provider local',
			'treeseed capacity down --market local --provider local',
			'treeseed capacity test-local',
		],
		help: {
			longSummary: ['Capacity reads Market project capacity diagnostics and durable agent-capacity coordination records, migrates provider setup toward derived native facts, and routes package-owned provider lifecycle resources through canonical reconciliation.'],
			whenToUse: ['Use this when inspecting native-to-credit projection, allocation-set versions, project agent classes, decision readiness, execution inputs, provider sessions, assignment lifecycle, mode-run telemetry, workday summaries, or the local provider stack.'],
			beforeYouRun: ['Build @treeseed/agent first, or pass --agent-package-root to a built package. Use `trsd config` for encrypted provider values; capacity commands do not write plaintext env files.'],
			automationNotes: ['Use `--json` for stable output. Assignment, mode-run, and assignment-explanation inspection includes read-only execution visibility and capability match summaries. `checkpoint-integrate` validates a completed reviewed assignment and copies its exact checkpoint lineage only into a clean unprotected task branch; `trsd save` remains a separate operator action. Use `--plan` for lifecycle previews and `--execute` for mutations. Registration-key reveal and rotation additionally require `--yes` in noninteractive automation.'],
		},
		helpVisible: true,
		helpFeatured: false,
		executionMode: 'handler',
		handlerName: 'capacity',
	},
	{
		id: 'hosting',
		name: 'hosting',
		aliases: [],
		group: 'Utilities',
		summary: 'Plan, apply, verify, and inspect the Treeseed hosting graph.',
		description: 'Resolve host-agnostic service types into environment-specific host bindings for local dev, staging, and production.',
		provider: 'default',
		related: ['status', 'dev', 'config', 'stage', 'release'],
		usage: 'treeseed hosting [status|plan|apply|verify|destroy] [--environment local|staging|prod] [--app web|api] [--service api] [--placement-only] [--replace-pending-volumes --yes] [--json]',
		arguments: [{ name: 'action', description: 'Hosting action.', required: false }],
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Hosting environment to resolve.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'app', flags: '--app <app-id>', description: 'Limit hosting graph work to one discovered Treeseed application, such as web or api.', kind: 'string' },
			{ name: 'service', flags: '--service <service-id>', description: 'Limit hosting graph work to one service id. Repeat or comma-separate for multiple services.', kind: 'string' },
			{ name: 'placement', flags: '--placement <placement>', description: 'Limit hosting graph work to one service placement.', kind: 'string' },
			{ name: 'host', flags: '--host <host-id>', description: 'Limit hosting graph work to one host id.', kind: 'string' },
			{ name: 'live', flags: '--live', description: 'Request live provider verification where supported.', kind: 'boolean' },
			{ name: 'placementOnly', flags: '--placement-only', description: 'Limit hosting plan output to deterministic placement compilation without provider-state reconciliation.', kind: 'boolean' },
			{ name: 'replacePendingVolumes', flags: '--replace-pending-volumes', description: 'Allow hosting apply to replace Railway volumes already queued for deletion. Permanently discards their data and requires --yes.', kind: 'boolean' },
			{ name: 'yes', flags: '--yes', description: 'Confirm an explicitly destructive hosting operation.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: [
			'treeseed hosting status --environment local',
			'treeseed hosting plan --environment staging --json',
			'treeseed hosting plan --environment staging --app web --json',
			'treeseed hosting plan --environment staging --app api --json',
			'treeseed hosting plan --environment staging --service api --json',
			'treeseed hosting verify --environment prod --json',
			'treeseed hosting apply --environment staging --app api --json',
			'treeseed hosting destroy --environment staging --app api --json',
		],
		help: {
			longSummary: ['Hosting resolves Treeseed application profiles into service placements, service types, host capabilities, and provider/local resources.'],
			whenToUse: ['Use this before dev, stage, or release when you need to inspect host bindings, missing capabilities, or TreeDX/public federation placement.'],
			beforeYouRun: ['Run from the Treeseed workspace. Use `--json` for automation. `plan` is non-mutating; `apply`, `verify --live`, and `destroy` operate on real hosted resources.'],
			automationNotes: ['The JSON report includes placements, units, selected hosts, required capabilities, project groups, and verification checks without secret values.'],
		},
		helpVisible: true,
		helpFeatured: true,
		executionMode: 'handler',
		handlerName: 'hosting',
	},
	{
		id: 'reconcile',
		name: 'reconcile',
		aliases: [],
		group: 'Utilities',
		summary: 'Run canonical reconciliation platform diagnostics.',
		description: 'Plan, apply, verify, destroy, and live-test SDK-owned exact-state reconciliation.',
		provider: 'default',
		related: ['hosting', 'config', 'stage', 'release'],
		usage: 'treeseed reconcile [plan|status|verify|apply|destroy|test-live] [--environment local|staging|prod] [--unit-id <id>] [--execute] [--json]',
		arguments: [{ name: 'action', description: 'Reconcile action.', required: false }],
		options: [
			{ name: 'provider', flags: '--provider <provider>', description: 'Provider live-test scope. Use railway, cloudflare, github, local, or all.', kind: 'string' },
			{ name: 'mode', flags: '--mode <mode>', description: 'Live-test mode. Smoke is read-only; acceptance and cleanup mutate isolated provider resources and require --yes.', kind: 'enum', values: ['smoke', 'acceptance', 'cleanup'] },
			{ name: 'environment', flags: '--environment <scope>', description: 'Environment to test.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'unitId', flags: '--unit-id <id>', description: 'Limit plan/apply/verify/destroy to one or more comma-separated desired unit ids.', kind: 'string' },
			{ name: 'unitType', flags: '--unit-type <type>', description: 'Limit plan/apply/verify/destroy to one or more desired unit types.', kind: 'string' },
			{ name: 'resourceKind', flags: '--resource-kind <kind>', description: 'Limit plan/apply/verify/destroy to one or more desired resource kinds.', kind: 'string' },
			{ name: 'packageId', flags: '--package-id <id>', description: 'Limit plan/apply/verify/destroy to one or more Treeseed package ids.', kind: 'string' },
			{ name: 'serviceId', flags: '--service-id <id>', description: 'Limit plan/apply/verify/destroy to one or more service ids.', kind: 'string' },
			{ name: 'serviceType', flags: '--service-type <type>', description: 'Limit plan/apply/verify/destroy to one or more service unit types.', kind: 'string' },
			{ name: 'execute', flags: '--execute', description: 'Allow reconcile apply or destroy to mutate provider resources.', kind: 'boolean' },
			{ name: 'yes', flags: '--yes', description: 'Confirm acceptance or cleanup mode may create and delete real isolated provider resources.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: [
			'treeseed reconcile plan --environment staging --json',
			'treeseed reconcile verify --environment staging --json',
			'treeseed reconcile apply --environment staging --json',
			'treeseed reconcile apply --environment staging --unit-id github-secret-binding:root:staging:TREESEED_CREDENTIAL_SESSION_SECRET --execute --json',
			'treeseed reconcile apply --environment staging --execute --json',
			'treeseed reconcile test-live --provider local --json',
			'treeseed reconcile test-live --provider railway --environment staging --json',
			'treeseed reconcile test-live --provider all --environment staging --json',
			'treeseed reconcile test-live --mode acceptance --provider railway --environment staging --yes --json',
			'treeseed reconcile test-live --mode cleanup --provider all --environment staging --yes --json',
		],
		help: {
			longSummary: ['Reconcile is the canonical SDK lifecycle for provider state: refresh, diff, plan, validate, apply, refresh, verify, and persist. Smoke mode is fast and read-only. Acceptance mode creates, updates, verifies, and destroys isolated resources. Cleanup mode removes leftover isolated live-test resources. Missing provider coverage is reported as blocking drift, not skipped success.'],
			whenToUse: ['Use this before staging or release promotions when provider tokens are configured, or when adding a new provider/resource adapter.'],
			beforeYouRun: ['Run from the Treeseed workspace. Provider tests use encrypted Treeseed config values and deterministic isolated prefixes.'],
			automationNotes: ['The JSON report contains the desired resource graph, package units, reconcile actions, postconditions, blocked drift, provider limitations, live verification, and ok state.'],
		},
		helpVisible: true,
		helpFeatured: false,
		executionMode: 'handler',
		handlerName: 'reconcile',
	},
];
