import type { TreeseedOperationSpec } from './operations-types.ts';

function command(spec: TreeseedOperationSpec): TreeseedOperationSpec {
	return spec;
}

export const TRESEED_OPERATION_SPECS: TreeseedOperationSpec[] = [
	command({
		id: 'workspace.status',
		name: 'status',
		aliases: [],
		group: 'Workflow',
		summary: 'Show Treeseed project health and the current task state.',
		description: 'Report branch/task state, doctor-style readiness, runtime configuration, preview/deploy state, auth readiness, and recommended next commands.',
		usage: 'treeseed status [--json]',
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed status', 'treeseed status --json'],
		related: ['tasks', 'switch', 'config'],
		executionMode: 'handler',
		handlerName: 'status',
	}),
	command({
		id: 'branch.tasks',
		name: 'tasks',
		aliases: [],
		group: 'Workflow',
		summary: 'List task branches and preview metadata.',
		description: 'List task-based preview Git branches from local and origin, excluding main, staging, and deprecated tags.',
		usage: 'treeseed tasks [--json]',
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed tasks', 'treeseed tasks --json'],
		related: ['status', 'switch', 'close'],
		executionMode: 'handler',
		handlerName: 'tasks',
	}),
	command({
		id: 'branch.switch',
		name: 'switch',
		aliases: [],
		group: 'Workflow',
		summary: 'Create or resume a task branch.',
		description: 'Create a new task branch from staging or resume an existing local/remote task branch, optionally provisioning a branch preview deployment.',
		usage: 'treeseed switch <branch-name> [--preview] [--json]',
		arguments: [{ name: 'branch-name', description: 'Task branch to create or resume.', required: true }],
		options: [
			{ name: 'preview', flags: '--preview', description: 'Provision or refresh a branch-scoped Cloudflare preview environment.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed switch feature/search-improvements', 'treeseed switch feature/search-improvements --preview'],
		related: ['tasks', 'dev', 'save'],
		executionMode: 'handler',
		handlerName: 'switch',
	}),
	command({
		id: 'branch.save',
		name: 'save',
		aliases: [],
		group: 'Workflow',
		summary: 'Verify, commit, sync, push, and refresh preview for the current task.',
		description: 'Run lint/test/build verification, commit the current task branch, pull/rebase from origin, report merge conflicts, push, and refresh the branch preview when one is enabled.',
		usage: 'treeseed save [--hotfix] <message> [--json]',
		arguments: [{ name: 'message', description: 'Git commit message for the save operation.', required: true, kind: 'message_tail' }],
		options: [
			{ name: 'hotfix', flags: '--hotfix', description: 'Allow save on main for an explicit hotfix.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed save "feat: add search filters"', 'treeseed save --hotfix "fix: unblock production form submit"'],
		related: ['switch', 'stage', 'status'],
		executionMode: 'handler',
		handlerName: 'save',
	}),
	command({
		id: 'branch.close',
		name: 'close',
		aliases: [],
		group: 'Workflow',
		summary: 'Archive a task branch without merging it.',
		description: 'Destroy branch preview resources, create a deprecated resurrection tag at the branch HEAD, push the tag, and delete the local/remote branch without merging to staging.',
		usage: 'treeseed close <message> [--json]',
		arguments: [{ name: 'message', description: 'Reason for closing the task without staging it.', required: true, kind: 'message_tail' }],
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed close "superseded by feature/search-v2"'],
		related: ['tasks', 'switch', 'stage'],
		executionMode: 'handler',
		handlerName: 'close',
	}),
	command({
		id: 'branch.stage',
		name: 'stage',
		aliases: [],
		group: 'Workflow',
		summary: 'Merge the current task into staging and clean it up.',
		description: 'Verify the current task branch, merge it into staging, wait for staging automation, clean preview resources, create a deprecated resurrection tag, and delete local/remote task branches.',
		usage: 'treeseed stage <message> [--json]',
		arguments: [{ name: 'message', description: 'Resolution message for the staged task.', required: true, kind: 'message_tail' }],
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed stage "feat: add search filters"'],
		related: ['save', 'release', 'close'],
		executionMode: 'handler',
		handlerName: 'stage',
	}),
	command({
		id: 'deploy.rollback',
		name: 'rollback',
		aliases: [],
		group: 'Workflow',
		summary: 'Roll back staging or production to a recorded deployment.',
		description: 'Redeploy a previously recorded staging or production commit using a temporary checkout of that revision.',
		usage: 'treeseed rollback <staging|prod> [--to <deploy-id|commit>] [--json]',
		arguments: [{ name: 'environment', description: 'The persistent environment to roll back.', required: true }],
		options: [
			{ name: 'to', flags: '--to <deploy-id|commit>', description: 'Explicit commit to roll back to. Defaults to the previous recorded deployment when omitted.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed rollback staging', 'treeseed rollback prod --to abc1234'],
		related: ['status', 'release'],
		executionMode: 'handler',
		handlerName: 'rollback',
	}),
	command({
		id: 'workspace.doctor',
		name: 'doctor',
		aliases: [],
		group: 'Validation',
		summary: 'Diagnose Treeseed tooling, auth, and workflow readiness.',
		description: 'Compatibility diagnostic command. `treeseed status` includes the primary doctor-style workflow summary.',
		usage: 'treeseed doctor [--fix] [--json]',
		options: [
			{ name: 'fix', flags: '--fix', description: 'Apply safe local repairs before rerunning diagnostics.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed doctor', 'treeseed doctor --fix --json'],
		related: ['status', 'config'],
		executionMode: 'handler',
		handlerName: 'doctor',
	}),
	command({
		id: 'auth.login',
		name: 'auth:login',
		aliases: [],
		group: 'Validation',
		summary: 'Authenticate the CLI against the configured Treeseed API.',
		description: 'Start the device login flow against the active Treeseed API host and persist the returned session locally.',
		usage: 'treeseed auth:login [--host <id>] [--json]',
		options: [
			{ name: 'host', flags: '--host <id>', description: 'Override the configured remote host id for this login.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed auth:login'],
		related: ['auth:check', 'auth:whoami', 'auth:logout'],
		executionMode: 'handler',
		handlerName: 'auth:login',
	}),
	command({
		id: 'auth.logout',
		name: 'auth:logout',
		aliases: [],
		group: 'Validation',
		summary: 'Clear locally stored Treeseed API credentials.',
		description: 'Remove the persisted local device-flow session for the active Treeseed API host.',
		usage: 'treeseed auth:logout [--host <id>] [--json]',
		options: [
			{ name: 'host', flags: '--host <id>', description: 'Override the configured remote host id to clear.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed auth:logout'],
		related: ['auth:login', 'auth:whoami'],
		executionMode: 'handler',
		handlerName: 'auth:logout',
	}),
	command({
		id: 'auth.whoami',
		name: 'auth:whoami',
		aliases: [],
		group: 'Validation',
		summary: 'Inspect the active Treeseed API identity.',
		description: 'Use the persisted local remote session to query the active Treeseed API principal.',
		usage: 'treeseed auth:whoami [--json]',
		options: [{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' }],
		examples: ['treeseed auth:whoami'],
		related: ['auth:login', 'status', 'doctor'],
		executionMode: 'handler',
		handlerName: 'auth:whoami',
	}),
	command({
		id: 'template.list',
		name: 'template',
		aliases: [],
		group: 'Utilities',
		summary: 'List, inspect, and validate templates from the remote Treeseed catalog.',
		description: 'Use the configured Treeseed template API to list templates, show details for one template, or validate locally shipped template artifacts against the remote catalog.',
		usage: 'treeseed template [list|show|validate] [id]',
		arguments: [
			{ name: 'action', description: 'Template action: list, show, or validate.', required: false },
			{ name: 'id', description: 'Template id for show or validate.', required: false },
		],
		examples: ['treeseed template', 'treeseed template list', 'treeseed template show starter-basic', 'treeseed template validate'],
		related: ['init', 'sync'],
		executionMode: 'handler',
		handlerName: 'template',
	}),
	command({
		id: 'template.sync',
		name: 'sync',
		aliases: [],
		group: 'Validation',
		summary: 'Validate or reconcile the managed template surface for the current site.',
		description: 'Use remote template metadata plus the local CLI template artifact to check or apply updates to the narrow core-managed scaffold surface.',
		usage: 'treeseed sync [--check]',
		options: [{ name: 'check', flags: '--check', description: 'Report managed-surface drift without changing files.', kind: 'boolean' }],
		examples: ['treeseed sync --check', 'treeseed sync'],
		related: ['template', 'init', 'status'],
		executionMode: 'handler',
		handlerName: 'sync',
	}),
	command({
		id: 'project.init',
		name: 'init',
		aliases: [],
		group: 'Workflow',
		summary: 'Scaffold a new Treeseed tenant project.',
		description: 'Create a new Treeseed tenant directory from a remote-catalog template backed by the local CLI scaffold artifact and print recommended next steps.',
		usage: 'treeseed init <directory> [--template <starter-id>] [--name <site-name>] [--slug <slug>] [--site-url <url>] [--contact-email <email>] [--repo <url>] [--discord <url>]',
		arguments: [{ name: 'directory', description: 'Target directory for the new tenant.', required: true }],
		options: [
			{ name: 'template', flags: '--template <starter-id>', description: 'Select the starter template id to generate. Defaults to starter-basic.', kind: 'string' },
			{ name: 'name', flags: '--name <site-name>', description: 'Override the generated site name.', kind: 'string' },
			{ name: 'slug', flags: '--slug <slug>', description: 'Override the generated package and tenant slug.', kind: 'string' },
			{ name: 'siteUrl', flags: '--site-url <url>', description: 'Set the initial public site URL.', kind: 'string' },
			{ name: 'contactEmail', flags: '--contact-email <email>', description: 'Set the site contact address.', kind: 'string' },
			{ name: 'repo', flags: '--repo <url>', description: 'Set the repository URL.', kind: 'string' },
			{ name: 'discord', flags: '--discord <url>', description: 'Set the Discord/community URL.', kind: 'string' },
		],
		examples: ['treeseed init docs-site --template starter-basic --name "Docs Site" --site-url https://docs.example.com'],
		notes: ['Runs outside an existing repo or from any branch.'],
		related: ['config', 'switch', 'dev'],
		executionMode: 'handler',
		handlerName: 'init',
	}),
	command({
		id: 'project.config',
		name: 'config',
		aliases: [],
		group: 'Workflow',
		summary: 'Configure and test the runtime foundation.',
		description: 'Apply safe repairs, collect environment values, write local machine config, generate local env files, initialize local/staging/prod foundations, sync providers, and run doctor-style checks.',
		usage: 'treeseed config [--environment <all|local|staging|prod>]... [--sync <none|github|cloudflare|railway|all>] [--print-env] [--print-env-only] [--show-secrets] [--rotate-machine-key]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Select all environments or limit configuration to local, staging, or prod. Defaults to all.', kind: 'enum', repeatable: true, values: ['all', 'local', 'staging', 'prod'] },
			{ name: 'sync', flags: '--sync <mode>', description: 'Sync hosted secrets/variables to GitHub, Cloudflare, Railway, or all providers. Defaults to all.', kind: 'enum', values: ['none', 'github', 'cloudflare', 'railway', 'all'] },
			{ name: 'printEnv', flags: '--print-env', description: 'Print resolved environment values before remote initialization.', kind: 'boolean' },
			{ name: 'printEnvOnly', flags: '--print-env-only', description: 'Print resolved environment values, check provider connections, and exit without prompting or initializing remote resources.', kind: 'boolean' },
			{ name: 'showSecrets', flags: '--show-secrets', description: 'Print full secret values in environment reports instead of masking them.', kind: 'boolean' },
			{ name: 'rotateMachineKey', flags: '--rotate-machine-key', description: 'Regenerate the local home machine key and re-encrypt stored Treeseed secrets and remote auth sessions.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed config', 'treeseed config --environment all', 'treeseed config --environment local --sync none', 'treeseed config --environment staging --print-env-only --show-secrets', 'treeseed config --rotate-machine-key'],
		notes: ['Does not create branch preview deployments. Use `treeseed switch <branch> --preview` for that.'],
		related: ['status', 'switch', 'dev'],
		executionMode: 'handler',
		handlerName: 'config',
	}),
	command({
		id: 'deploy.release',
		name: 'release',
		aliases: [],
		group: 'Workflow',
		summary: 'Promote staging to production with a version bump.',
		description: 'Validate staging, apply exactly one version bump, tag the release, merge staging into main, push, and rely on production deploy automation.',
		usage: 'treeseed release --major|--minor|--patch',
		options: [
			{ name: 'major', flags: '--major', description: 'Bump to the next major version.', kind: 'boolean' },
			{ name: 'minor', flags: '--minor', description: 'Bump to the next minor version.', kind: 'boolean' },
			{ name: 'patch', flags: '--patch', description: 'Bump to the next patch version.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed release --patch', 'treeseed release --minor'],
		notes: ['Requires exactly one bump flag.'],
		related: ['stage', 'status', 'rollback'],
		executionMode: 'handler',
		handlerName: 'release',
	}),
	command({
		id: 'deploy.destroy',
		name: 'destroy',
		aliases: [],
		group: 'Workflow',
		summary: 'Destroy a persistent environment and its local state.',
		description: 'Delete the selected persistent environment resources and remove the local deploy state after confirmation.',
		usage: 'treeseed destroy --environment <local|staging|prod> [--dry-run] [--force] [--skip-confirmation] [--confirm <slug>] [--remove-build-artifacts]',
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Select the persistent environment to destroy.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'dryRun', flags: '--dry-run', description: 'Preview the destroy operation.', kind: 'boolean' },
			{ name: 'force', flags: '--force', description: 'Force worker deletion when supported.', kind: 'boolean' },
			{ name: 'skipConfirmation', flags: '--skip-confirmation', description: 'Skip the interactive confirmation prompt.', kind: 'boolean' },
			{ name: 'confirm', flags: '--confirm <slug>', description: 'Provide the expected slug confirmation non-interactively.', kind: 'string' },
			{ name: 'removeBuildArtifacts', flags: '--remove-build-artifacts', description: 'Also remove local build artifacts after destroy.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed destroy --environment staging --dry-run', 'treeseed destroy --environment prod --confirm example --skip-confirmation'],
		notes: ['Only for persistent environments. Task cleanup belongs to treeseed close.', 'This command is destructive and requires explicit confirmation.'],
		related: ['config', 'status'],
		executionMode: 'handler',
		handlerName: 'destroy',
	}),
	command({ id: 'local.dev', name: 'dev', aliases: [], group: 'Local Development', summary: 'Start the unified local Treeseed development environment.', description: 'Start the unified local Treeseed development environment.', examples: ['treeseed dev'], executionMode: 'handler', handlerName: 'dev' }),
	command({ id: 'local.devWatch', name: 'dev:watch', aliases: [], group: 'Local Development', summary: 'Start local development with rebuild/watch mode.', description: 'Start local development with rebuild/watch mode.', examples: ['treeseed dev:watch'], executionMode: 'handler', handlerName: 'dev' }),
	command({ id: 'local.build', name: 'build', aliases: [], group: 'Local Development', summary: 'Build the tenant site and generated worker artifacts.', description: 'Build the tenant site and generated worker artifacts.', examples: ['treeseed build'], executionMode: 'adapter', adapter: { script: 'tenant-build' } }),
	command({ id: 'local.check', name: 'check', aliases: [], group: 'Local Development', summary: 'Run the tenant check flow.', description: 'Run the tenant check flow.', examples: ['treeseed check'], executionMode: 'adapter', adapter: { script: 'tenant-check' } }),
	command({ id: 'local.preview', name: 'preview', aliases: [], group: 'Local Development', summary: 'Preview the built tenant site locally.', description: 'Preview the built tenant site locally.', examples: ['treeseed preview'], executionMode: 'adapter', adapter: { script: 'tenant-astro-command', passthroughArgs: true } }),
	command({ id: 'local.lint', name: 'lint', aliases: [], group: 'Validation', summary: 'Run Treeseed lint checks.', description: 'Run Treeseed lint checks.', examples: ['treeseed lint'], executionMode: 'adapter', adapter: { directScript: 'tenant-lint', workspaceScript: 'workspace-lint', script: 'tenant-lint' } }),
	command({ id: 'local.test', name: 'test', aliases: [], group: 'Validation', summary: 'Run Treeseed tests.', description: 'Run Treeseed tests.', examples: ['treeseed test'], executionMode: 'adapter', adapter: { directScript: 'tenant-test', workspaceScript: 'workspace-test', script: 'tenant-test' } }),
	command({ id: 'validation.testUnit', name: 'test:unit', aliases: [], group: 'Validation', summary: 'Run workspace unit tests in dependency order.', description: 'Run workspace unit tests in dependency order.', examples: ['treeseed test:unit'], executionMode: 'adapter', adapter: { script: 'workspace-test-unit', requireWorkspaceRoot: true } }),
	command({ id: 'validation.preflight', name: 'preflight', aliases: [], group: 'Validation', summary: 'Check local CLI prerequisites and authentication state.', description: 'Check local CLI prerequisites and authentication state.', examples: ['treeseed preflight'], executionMode: 'adapter', adapter: { script: 'workspace-preflight', requireWorkspaceRoot: true } }),
	command({ id: 'validation.authCheck', name: 'auth:check', aliases: [], group: 'Validation', summary: 'Check CLI prerequisites and require authenticated tooling.', description: 'Check CLI prerequisites and require authenticated tooling.', examples: ['treeseed auth:check'], executionMode: 'adapter', adapter: { script: 'workspace-preflight', extraArgs: ['--require-auth'], requireWorkspaceRoot: true } }),
	command({ id: 'release.testE2e', name: 'test:e2e', aliases: [], group: 'Release Utilities', summary: 'Run Treeseed end-to-end command tests.', description: 'Run Treeseed end-to-end command tests.', examples: ['treeseed test:e2e'], executionMode: 'adapter', adapter: { script: 'workspace-command-e2e', requireWorkspaceRoot: true } }),
	command({ id: 'release.testE2eLocal', name: 'test:e2e:local', aliases: [], group: 'Release Utilities', summary: 'Run local-mode Treeseed end-to-end command tests.', description: 'Run local-mode Treeseed end-to-end command tests.', examples: ['treeseed test:e2e:local'], executionMode: 'adapter', adapter: { script: 'workspace-command-e2e', extraArgs: ['--mode=local'], requireWorkspaceRoot: true } }),
	command({ id: 'release.testE2eStaging', name: 'test:e2e:staging', aliases: [], group: 'Release Utilities', summary: 'Run staging-mode Treeseed end-to-end command tests.', description: 'Run staging-mode Treeseed end-to-end command tests.', examples: ['treeseed test:e2e:staging'], executionMode: 'adapter', adapter: { script: 'workspace-command-e2e', extraArgs: ['--mode=staging'], requireWorkspaceRoot: true } }),
	command({ id: 'release.testE2eFull', name: 'test:e2e:full', aliases: [], group: 'Release Utilities', summary: 'Run the full Treeseed end-to-end command suite.', description: 'Run the full Treeseed end-to-end command suite.', examples: ['treeseed test:e2e:full'], executionMode: 'adapter', adapter: { script: 'workspace-command-e2e', extraArgs: ['--mode=full'], requireWorkspaceRoot: true } }),
	command({ id: 'release.testFast', name: 'test:release', aliases: [], group: 'Release Utilities', summary: 'Run the fast release verification path.', description: 'Run the fast release verification path.', examples: ['treeseed test:release'], executionMode: 'adapter', adapter: { script: 'workspace-release-verify', requireWorkspaceRoot: true } }),
	command({ id: 'release.verify', name: 'test:release:full', aliases: ['release:verify'], group: 'Release Utilities', summary: 'Run the full release verification path.', description: 'Run the full release verification path.', examples: ['treeseed test:release:full', 'treeseed release:verify'], executionMode: 'adapter', adapter: { script: 'workspace-release-verify', extraArgs: ['--full-smoke'], requireWorkspaceRoot: true } }),
	command({ id: 'release.publishChanged', name: 'release:publish:changed', aliases: [], group: 'Release Utilities', summary: 'Publish changed Treeseed workspace packages.', description: 'Publish changed Treeseed workspace packages.', examples: ['treeseed release:publish:changed'], executionMode: 'adapter', adapter: { script: 'workspace-publish-changed-packages', requireWorkspaceRoot: true } }),
	command({ id: 'tools.astro', name: 'astro', aliases: [], group: 'Passthrough', summary: 'Pass through to the packaged Astro CLI wrapper.', description: 'Pass through to the packaged Astro CLI wrapper.', examples: ['treeseed astro -- --help'], executionMode: 'adapter', adapter: { script: 'tenant-astro-command', passthroughArgs: true } }),
	command({ id: 'tools.syncDevvars', name: 'sync:devvars', aliases: [], group: 'Utilities', summary: 'Regenerate .dev.vars from local configuration.', description: 'Regenerate .dev.vars from local configuration.', examples: ['treeseed sync:devvars'], executionMode: 'adapter', adapter: { script: 'sync-dev-vars' } }),
	command({ id: 'services.mailpitUp', name: 'mailpit:up', aliases: [], group: 'Utilities', summary: 'Start the package-managed Mailpit service.', description: 'Start the package-managed Mailpit service.', examples: ['treeseed mailpit:up'], executionMode: 'adapter', adapter: { script: 'ensure-mailpit' } }),
	command({ id: 'services.mailpitDown', name: 'mailpit:down', aliases: [], group: 'Utilities', summary: 'Stop the package-managed Mailpit service.', description: 'Stop the package-managed Mailpit service.', examples: ['treeseed mailpit:down'], executionMode: 'adapter', adapter: { script: 'stop-mailpit' } }),
	command({ id: 'services.mailpitLogs', name: 'mailpit:logs', aliases: [], group: 'Utilities', summary: 'Show Mailpit logs.', description: 'Show Mailpit logs.', examples: ['treeseed mailpit:logs'], executionMode: 'adapter', adapter: { script: 'logs-mailpit' } }),
	command({ id: 'data.d1MigrateLocal', name: 'd1:migrate:local', aliases: [], group: 'Utilities', summary: 'Apply local D1 migrations.', description: 'Apply local D1 migrations.', examples: ['treeseed d1:migrate:local'], executionMode: 'adapter', adapter: { script: 'tenant-d1-migrate-local' } }),
	command({ id: 'content.cleanupMarkdown', name: 'cleanup:markdown', aliases: [], group: 'Utilities', summary: 'Normalize Markdown and MDX files.', description: 'Normalize Markdown and MDX files.', examples: ['treeseed cleanup:markdown docs/README.md'], executionMode: 'adapter', adapter: { script: 'cleanup-markdown', rewriteArgs: (args) => ['--write', ...args] } }),
	command({ id: 'content.cleanupMarkdownCheck', name: 'cleanup:markdown:check', aliases: [], group: 'Utilities', summary: 'Check Markdown and MDX formatting without rewriting files.', description: 'Check Markdown and MDX formatting without rewriting files.', examples: ['treeseed cleanup:markdown:check docs/README.md'], executionMode: 'adapter', adapter: { script: 'cleanup-markdown', rewriteArgs: (args) => ['--check', ...args] } }),
	command({ id: 'tools.starlightPatch', name: 'starlight:patch', aliases: [], group: 'Utilities', summary: 'Apply the Starlight content path patch.', description: 'Apply the Starlight content path patch.', examples: ['treeseed starlight:patch'], executionMode: 'adapter', adapter: { script: 'patch-starlight-content-path' } }),
];

export const TRESEED_OPERATION_INDEX = new Map<string, TreeseedOperationSpec>();
for (const spec of TRESEED_OPERATION_SPECS) {
	TRESEED_OPERATION_INDEX.set(spec.name, spec);
	for (const alias of spec.aliases) TRESEED_OPERATION_INDEX.set(alias, spec);
}

export function findTreeseedOperation(name: string | null | undefined) {
	if (!name) return null;
	return TRESEED_OPERATION_INDEX.get(name) ?? null;
}

export function listTreeseedOperationNames() {
	return [...new Set(TRESEED_OPERATION_SPECS.map((spec) => spec.name))];
}
