import type { TreeseedOperationSpec } from './operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from './operations-registry-support.ts';

export const providerToolsOperationSpecs: TreeseedOperationSpec[] = [
	{
			id: 'tools.gh',
			name: 'gh',
			aliases: [],
			group: 'Passthrough',
			summary: 'Run the managed GitHub CLI with Treeseed environment credentials.',
			description: 'Decrypt Treeseed machine configuration for the selected environment and pass it to the managed GitHub CLI.',
			provider: 'default',
			related: ['tools', 'install', 'config'],
			usage: 'treeseed gh [--environment staging] -- <gh-args>',
			arguments: [{ name: 'args', description: 'Arguments forwarded to GitHub CLI.', required: false }],
			options: TOOL_WRAPPER_OPTIONS,
			examples: ['treeseed gh --environment staging -- run list --limit 5', 'treeseed gh -- repo view'],
			help: {
				longSummary: ['The GitHub wrapper resolves the Treeseed-managed `gh` executable, decrypts scoped machine configuration, and passes the resulting GitHub token only to the child process environment.'],
				whenToUse: ['Use this when provider auth lives in Treeseed machine config rather than your shell environment.'],
				beforeYouRun: ['Run from a Treeseed project. Use `--environment staging` unless you intentionally need local or production credentials.'],
				automationNotes: ['Use `--` before target CLI flags when a flag could be parsed by Treeseed itself. The wrapper does not print decrypted secrets.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'gh',
		},
	{
			id: 'tools.railway',
			name: 'railway',
			aliases: [],
			group: 'Passthrough',
			summary: 'Run the managed Railway CLI with Treeseed environment credentials.',
			description: 'Decrypt Treeseed machine configuration for the selected environment, select the matching Railway environment, and pass it to the managed Railway CLI.',
			provider: 'default',
			related: ['tools', 'install', 'config'],
			usage: 'treeseed railway [--environment staging] -- <railway-args>',
			arguments: [{ name: 'args', description: 'Arguments forwarded to Railway CLI.', required: false }],
			options: TOOL_WRAPPER_OPTIONS,
			examples: ['treeseed railway --environment staging -- whoami', 'treeseed railway --environment staging -- status', 'treeseed railway --environment prod -- status'],
			help: {
				longSummary: ['The Railway wrapper resolves the Treeseed-managed Railway executable, decrypts scoped machine configuration, selects the requested Railway environment, and passes the resulting Railway token only to the child process environment.'],
				whenToUse: ['Use this to debug Railway projects and service builds with Treeseed-managed `TREESEED_RAILWAY_API_TOKEN`, translated to `RAILWAY_API_TOKEN` only for the Railway child process.'],
				beforeYouRun: ['Run from a Treeseed project. Use `--environment staging` when inspecting staging deployments and `--environment prod` when inspecting Railway production.'],
				automationNotes: ['Use `--` before target CLI flags when a flag could be parsed by Treeseed itself. The wrapper does not print decrypted secrets.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'railway',
		},
	{
			id: 'tools.wrangler',
			name: 'wrangler',
			aliases: [],
			group: 'Passthrough',
			summary: 'Run the managed Wrangler CLI with Treeseed environment credentials.',
			description: 'Decrypt Treeseed machine configuration for the selected environment and pass it to the managed Wrangler CLI.',
			provider: 'default',
			related: ['tools', 'install', 'config'],
			usage: 'treeseed wrangler [--environment staging] -- <wrangler-args>',
			arguments: [{ name: 'args', description: 'Arguments forwarded to Wrangler CLI.', required: false }],
			options: TOOL_WRAPPER_OPTIONS,
			examples: ['treeseed wrangler --environment staging -- whoami', 'treeseed wrangler --environment staging -- d1 list'],
			help: {
				longSummary: ['The Wrangler wrapper resolves the Treeseed-managed Wrangler executable, decrypts scoped machine configuration, and passes the resulting Cloudflare token and account settings only to the child process environment.'],
				whenToUse: ['Use this to debug Cloudflare resources with Treeseed-managed `TREESEED_CLOUDFLARE_API_TOKEN` and `TREESEED_CLOUDFLARE_ACCOUNT_ID`, translated to Cloudflare-native names only for the Wrangler child process.'],
				beforeYouRun: ['Run from a Treeseed project. Use `--environment staging` when inspecting staging resources.'],
				automationNotes: ['Use `--` before target CLI flags when a flag could be parsed by Treeseed itself. The wrapper does not print decrypted secrets.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'wrangler',
		},
	{
			id: 'tools.docker',
			name: 'docker',
			aliases: [],
			group: 'Passthrough',
			summary: 'Run Docker with Treeseed DockerHub credentials.',
			description: 'Decrypt Treeseed machine configuration for the selected environment, authenticate Docker with an isolated config directory, and forward arguments to Docker.',
			provider: 'default',
			related: ['tools', 'install', 'config'],
			usage: 'treeseed docker [--environment staging] -- <docker-args>',
			arguments: [{ name: 'args', description: 'Arguments forwarded to Docker.', required: false }],
			options: TOOL_WRAPPER_OPTIONS,
			examples: ['treeseed docker --environment prod -- buildx imagetools inspect treeseed/agent-api:1.2.3', 'treeseed docker --environment prod -- manifest inspect treeseed/agent-runner:1.2.3'],
			help: {
				longSummary: ['The Docker wrapper resolves Docker, decrypts scoped Treeseed DockerHub credentials, logs in through an isolated `DOCKER_CONFIG`, and forwards Docker arguments without printing secrets.'],
				whenToUse: ['Use this for authenticated DockerHub manifest checks, image pulls, and emergency image publication diagnostics. Official image publication should still use package image reconciliation unless explicitly repairing a blocked provider state.'],
				beforeYouRun: ['Run from a Treeseed project. Use `--environment staging` or `--environment prod` for hosted image checks. API and operations runner staging services deploy from Railway Git source builds; production uses Docker images produced by release workflows.'],
				automationNotes: ['Use `--` before target Docker flags when a flag could be parsed by Treeseed itself. The wrapper removes its temporary Docker config after the command exits.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'docker',
		},
];
