import type { TreeseedOperationSpec } from './operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from './operations-registry-support.ts';

export const marketProjectsOperationSpecs: TreeseedOperationSpec[] = [
	{
			id: 'market.registry',
			name: 'market',
			aliases: [],
			group: 'Utilities',
			summary: 'Manage configured Treeseed API endpoints.',
			description: 'List, add, select, remove, and inspect API profiles stored in local machine configuration.',
			provider: 'default',
			related: ['auth:login', 'teams', 'projects'],
			usage: 'treeseed market [list|add|use|remove|status]',
			arguments: [{ name: 'action', description: 'Market action.', required: false }],
			options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
				{ name: 'label', flags: '--label <label>', description: 'Display label for market add.', kind: 'string' },
				{ name: 'kind', flags: '--kind <kind>', description: 'Market kind for market add.', kind: 'enum', values: ['central', 'specialized'] },
				{ name: 'team', flags: '--team <team-id>', description: 'Team id for a specialized market profile.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: ['treeseed market list', 'treeseed market add enterprise https://market.example.com', 'treeseed market use central'],
			help: {
				longSummary: ['Market manages local Treeseed API profiles. It never serves market behavior itself; it only selects endpoints the SDK market client should call.'],
				whenToUse: ['Use this when you need to add an enterprise market, switch back to central, or inspect which market endpoint CLI commands will target.'],
				beforeYouRun: ['Decide whether you are managing the always-available central profile or a team-specific specialized market profile.'],
				automationNotes: ['Use `--json` when scripts need the active market id, URL, and configured profiles.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'market',
		},
	{
			id: 'market.teams',
			name: 'teams',
			aliases: [],
			group: 'Utilities',
			summary: 'Inspect teams from the selected market.',
			description: 'List teams, select a team context, and inspect team membership through the API client.',
			provider: 'default',
			related: ['market', 'auth:login', 'projects'],
			usage: 'treeseed teams [list|use|members]',
			arguments: [{ name: 'action', description: 'Teams action.', required: false }],
			options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
				{ name: 'team', flags: '--team <team-id>', description: 'Team id for member lookup.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: ['treeseed teams list', 'treeseed teams members team_123'],
			help: {
				longSummary: ['Teams reads team membership data from the selected API using the SDK market client.'],
				whenToUse: ['Use this after login to confirm team membership or inspect who belongs to a market-owned team.'],
				beforeYouRun: ['Authenticate to the selected market with `treeseed auth:login --market <id>` before reading private team data.'],
				automationNotes: ['Use `--json` for scripts that need stable team or member arrays.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'teams',
		},
	{
			id: 'market.projects',
			name: 'projects',
			aliases: [],
			group: 'Utilities',
			summary: 'Inspect projects, import repositories, project hosts, and web deployment operations from the selected market.',
			description: 'List market projects, plan/import existing GitHub repositories, inspect access and host bindings, and queue project host or web deployment operations through the API.',
			provider: 'default',
			related: ['market', 'teams', 'config'],
			usage: 'treeseed projects [list|access|hosts|import|deploy|publish|monitor|deployments|deployment]',
			arguments: [
				{ name: 'action', description: 'Projects action.', required: false },
				{ name: 'project-id', description: 'Project id for deployment and access actions.', required: false },
				{ name: 'deployment-id', description: 'Deployment id for deployment detail, retry, resume, or cancel.', required: false },
			],
			options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
				{ name: 'team', flags: '--team <team-id>', description: 'Limit project list to a team.', kind: 'string' },
				{ name: 'plan', flags: '--plan', description: 'For `projects import`, print the safe import plan without mutating TreeSeed records.', kind: 'boolean' },
				{ name: 'execute', flags: '--execute', description: 'For `projects import`, apply the safe import plan through the selected market API.', kind: 'boolean' },
				{ name: 'rootPath', flags: '--root-path <path>', description: 'Repository-relative project root override for `projects import`.', kind: 'string' },
				{ name: 'sitePath', flags: '--site-path <path>', description: 'Repository-relative site implementation path override for `projects import`.', kind: 'string' },
				{ name: 'contentPath', flags: '--content-path <path>', description: 'Repository-relative content path override for `projects import`.', kind: 'string' },
				{ name: 'visibility', flags: '--visibility <public|private>', description: 'Project visibility override for `projects import`.', kind: 'enum', values: ['public', 'private'] },
				{ name: 'credentialRef', flags: '--credential-ref <env:TREESEED_GITHUB_TOKEN...>', description: 'Credential reference for `projects import`; token values are never stored in the import plan.', kind: 'string' },
				{ name: 'environment', flags: '--environment <environment>', description: 'Deployment environment for project web actions.', kind: 'enum', values: ['staging', 'prod'] },
				{ name: 'wait', flags: '--wait', description: 'Poll the queued deployment until it reaches a terminal state.', kind: 'boolean' },
				{ name: 'timeoutSeconds', flags: '--timeout-seconds <seconds>', description: 'Maximum seconds to wait before returning timeout.', kind: 'string' },
				{ name: 'pollIntervalMs', flags: '--poll-interval-ms <milliseconds>', description: 'Polling interval for --wait.', kind: 'string' },
				{ name: 'reason', flags: '--reason <text>', description: 'Presentation-safe reason stored on the deployment request.', kind: 'string' },
				{ name: 'idempotencyKey', flags: '--idempotency-key <key>', description: 'Deterministic idempotency key for the deployment request.', kind: 'string' },
				{ name: 'requirement', flags: '--requirement <key>', description: 'Launch host requirement key for project host resync or rotate operations.', kind: 'string' },
				{ name: 'host', flags: '--host <requirement=provider:host-id>', description: 'Replacement host binding for `projects hosts replace`. Use requirement=provider:managed for a managed host or requirement=none for optional hosts.', kind: 'string', repeatable: true },
				{ name: 'sensitivePassphrase', flags: '--sensitive-passphrase <passphrase>', description: 'Deprecated fail-closed compatibility flag. Project host operations require client-side re-entry or migration instead of API passphrase submission.', kind: 'string' },
				{ name: 'yes', flags: '--yes', description: 'Required confirmation for production deploy and publish actions.', kind: 'boolean' },
				{ name: 'limit', flags: '--limit <count>', description: 'Maximum number of deployments to list.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: [
				'treeseed projects list',
				'treeseed projects import treeseed-ai/sdk --team treeseed --plan --json',
				'treeseed projects import knowledge-coop/market --team treeseed --site-path . --visibility private --execute --json',
				'treeseed projects access project_123',
				'treeseed projects hosts project_123',
				'treeseed projects hosts audit project_123',
				'treeseed projects hosts replace project_123 --host publicWeb=cloudflare:web-host-123',
				'treeseed projects deploy project_123 --environment staging --wait',
				'treeseed projects publish project_123 --environment prod --yes',
				'treeseed projects deployments project_123 --json',
				'treeseed projects deployment project_123 dep_123',
			],
			help: {
				longSummary: ['Projects reads project, host binding, access, and deployment state from the selected API using the SDK market client.'],
				whenToUse: ['Use this to inspect projects, audit or replace launch host bindings, queue staging or production web deployment operations, and inspect the same state shown in the Market UI.'],
				beforeYouRun: ['Authenticate to the market with `treeseed auth:login --market <selector>` and know the project id before queueing deployment work.'],
				automationNotes: ['Use `--json` to capture project lists, deployment records, events, and wait results for automation.'],
				warnings: ['Production deploy and publish require `--yes`; without it the CLI exits before calling the API.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'projects',
		},
];
