import type { TreeseedOperationSpec } from './operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from './operations-registry-support.ts';

export const CLI_ONLY_OPERATION_SPECS_4: TreeseedOperationSpec[] = [
	{
		id: 'ready',
		name: 'ready',
		aliases: [],
		group: 'Workflow',
		summary: 'Check whether an environment is ready for staging or release.',
		description: 'Runs deployment graph readiness, hosted service checks, and Treeseed operations runner smoke diagnostics before expensive workflow promotion.',
		provider: 'default',
		related: ['hosting', 'stage', 'release', 'doctor'],
		usage: 'treeseed ready <local|staging|prod> [--live] [--strict] [--json]',
		arguments: [{ name: 'environment', description: 'Environment to check.', required: false }],
		options: [
			{ name: 'environment', flags: '--environment <scope>', description: 'Environment to check.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'live', flags: '--live', description: 'Include live provider and HTTP checks.', kind: 'boolean' },
			{ name: 'strict', flags: '--strict', description: 'Fail when required live observations are unavailable.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: [
			'treeseed ready staging --json',
			'treeseed ready prod --json',
		],
		help: {
			longSummary: ['Ready is the fail-fast preflight for stage and release. It checks the effective hosting graph, provider state, HTTP health, and runner operation processing before a workflow spends time on deploys.'],
			whenToUse: ['Run before stage or release, especially after hosting config or package boundary changes.'],
			beforeYouRun: ['Run from the Treeseed workspace. Use `ready local` for static local checks, and use staging or prod only when provider credentials are available for live checks.'],
			automationNotes: ['Use --json for stable readiness output. Staging and prod default to live strict checks.'],
		},
		helpVisible: true,
		helpFeatured: true,
		executionMode: 'handler',
		handlerName: 'ready',
	},
	{
		id: 'operations',
		name: 'operations',
		aliases: [],
		group: 'Utilities',
		summary: 'Run Treeseed operation-runner diagnostics.',
		description: 'Queues a diagnostic Market platform operation and verifies that the deployed operations runner claims and completes it.',
		provider: 'default',
		related: ['hosting', 'ready', 'stage'],
			usage: 'treeseed operations smoke [--environment local|staging|prod] [--service operationsRunner] [--json]',
		arguments: [{ name: 'action', description: 'Operations action.', required: false }],
		options: [
				{ name: 'environment', flags: '--environment <scope>', description: 'Environment to smoke test.', kind: 'enum', values: ['local', 'staging', 'prod'] },
			{ name: 'service', flags: '--service <service-id>', description: 'Service to smoke test. Currently operationsRunner.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: [
				'treeseed operations smoke --environment local --service operationsRunner --json',
				'treeseed operations smoke --environment staging --service operationsRunner --json',
			],
			help: {
				longSummary: ['Operations smoke proves that the API, database, and operations runner work together before TreeDX/bootstrap workflows queue real work.'],
				whenToUse: ['Run when local or hosted operations stay queued, or before release resource verification.'],
				beforeYouRun: ['For local, start managed dev with `treeseed dev start --web-runtime local`. For hosted environments, run after the API and operations runner are deployed and configured through Treeseed config.'],
				automationNotes: ['The JSON report redacts credentials and includes operation id, final status, runner id, timings, and failure remediation.'],
			},
		helpVisible: true,
		helpFeatured: true,
		executionMode: 'handler',
		handlerName: 'operations',
	},
	{
		id: 'workflow.dispatch',
		name: 'workflow',
		aliases: [],
		group: 'Utilities',
		summary: 'Plan or dispatch a GitHub Actions workflow through reconciliation.',
		description: 'Triggers a workflow_dispatch run through the github-workflow-dispatch reconcile adapter so package and root workflows can be tested without pushing commits.',
		provider: 'default',
		related: ['package', 'gh', 'ci'],
		usage: 'treeseed workflow dispatch --repo <owner/name> --workflow <file> [--branch <ref>] [--input key=value]... [--execute] [--wait] [--json]',
		arguments: [{ name: 'action', description: 'Workflow action. Use dispatch.', required: false }],
		options: [
			{ name: 'repo', flags: '--repo <owner/name>', description: 'GitHub repository that owns the workflow.', kind: 'string' },
			{ name: 'repository', flags: '--repository <owner/name>', description: 'Alias for --repo.', kind: 'string' },
			{ name: 'workflow', flags: '--workflow <file>', description: 'Workflow file name or path, such as release-gate.yml.', kind: 'string' },
			{ name: 'branch', flags: '--branch <ref>', description: 'Branch or ref to dispatch. Defaults to staging.', kind: 'string' },
			{ name: 'ref', flags: '--ref <ref>', description: 'Alias for --branch.', kind: 'string' },
			{ name: 'input', flags: '--input <key=value>', description: 'workflow_dispatch input. Repeat for multiple inputs.', kind: 'string', repeatable: true },
			{ name: 'plan', flags: '--plan', description: 'Observe and plan without dispatching. This is the default when --execute is omitted.', kind: 'boolean' },
			{ name: 'execute', flags: '--execute', description: 'Dispatch the workflow. Without this flag, only plan and observe.', kind: 'boolean' },
			{ name: 'wait', flags: '--wait', description: 'Wait for the dispatched run to finish. Defaults to on when --execute is used.', kind: 'boolean' },
			{ name: 'timeout', flags: '--timeout <seconds>', description: 'Wait timeout in seconds when --wait is active.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable output.', kind: 'boolean' },
		],
		examples: [
			'treeseed workflow dispatch --repo treeseed-ai/agent --workflow release-gate.yml --branch staging --plan --json',
			'treeseed workflow dispatch --repo treeseed-ai/agent --workflow release-gate.yml --branch staging --execute --json',
		],
		help: {
			longSummary: ['Workflow dispatch is a generic reconciler-backed way to run workflow_dispatch workflows without creating a new commit or push. It uses the same GitHub credential routing and adapter lifecycle as package image publication.'],
			whenToUse: ['Use this to test release-gate workflows or no-op diagnostic workflows from the CLI when a push-triggered run is unnecessary.'],
			beforeYouRun: ['Make sure the selected repository has a Treeseed repository-scoped GitHub token with Actions write permission when dispatching outside the root repository. Plan mode is safe and reports credential blockers.'],
			automationNotes: ['Without --execute this command only refreshes and plans. With --execute it dispatches through github-workflow-dispatch and waits by default so failures are visible in the command result.'],
		},
		helpVisible: true,
		helpFeatured: false,
		executionMode: 'handler',
		handlerName: 'workflow',
	},
	{
		id: 'workspace.package',
		name: 'package',
		aliases: [],
		group: 'Utilities',
		summary: 'Run manifest-driven package workflow planning.',
		description: 'Validate package manifests and plan deployment source/image behavior declared by treeseed.package.yaml.',
		provider: 'default',
		related: ['config', 'hosting', 'db'],
		usage: 'treeseed package [validate|artifact build|artifact verify|artifact hydrate|image|workflow sync] [--package <package-id>]',
		arguments: [{ name: 'action', description: 'Package workflow action.', required: false }],
		options: [
			{ name: 'package', flags: '--package <package-id>', description: 'Discovered package id from treeseed.package.yaml, such as treedx.', kind: 'string' },
			{ name: 'packageRoot', flags: '--package-root <path>', description: 'Package checkout used to build an immutable artifact.', kind: 'string' },
			{ name: 'output', flags: '--output <path>', description: 'Directory for package tarball and integrity manifest output.', kind: 'string' },
			{ name: 'manifest', flags: '--manifest <path>', description: 'Package artifact integrity manifest to verify.', kind: 'string' },
			{ name: 'artifact', flags: '--artifact <path>', description: 'Optional tarball path overriding the manifest-relative artifact.', kind: 'string' },
			{ name: 'artifactsRoot', flags: '--artifacts-root <path>', description: 'Directory containing candidate package artifact manifests.', kind: 'string' },
			{ name: 'projectRoot', flags: '--project-root <path>', description: 'Project whose installed package graph receives candidate artifacts.', kind: 'string' },
			{ name: 'branch', flags: '--branch <branch>', description: 'Package repository branch/ref for source-build planning. Defaults to staging.', kind: 'string' },
			{ name: 'workflow', flags: '--workflow <file>', description: 'GitHub Actions workflow file for package image publication. Defaults to the package manifest.', kind: 'string' },
			{ name: 'syncConfig', flags: '--sync-config', description: 'Sync package image credentials from Treeseed config into the package GitHub environment.', kind: 'boolean' },
			{ name: 'plan', flags: '--plan', description: 'Print the package image plan without dispatching GitHub Actions.', kind: 'boolean' },
			{ name: 'execute', flags: '--execute', description: 'Dispatch a production image workflow when the package policy allows image publication.', kind: 'boolean' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: [
			'treeseed package validate --json',
			'treeseed package artifact build --output .treeseed/artifacts/package --json',
			'treeseed package artifact verify --manifest .treeseed/artifacts/package/manifest.json --json',
			'treeseed package artifact hydrate --artifacts-root .treeseed/artifacts/packages --project-root . --json',
			'treeseed package workflow sync --package all --plan --json',
			'treeseed package image --package treedx --branch staging --plan --json',
			'treeseed package image --package treedx --branch main --plan --json',
		],
		help: {
			longSummary: ['Package workflows are driven by package-local metadata instead of bespoke CLI logic. A checked-out package can declare its repository, production image workflow, hosting source mode, and credential requirements in treeseed.package.yaml.'],
			whenToUse: ['Use this to validate source-build staging behavior or production semantic image publication for packages such as TreeDX.'],
			beforeYouRun: ['Run `trsd config` to configure repository-scoped GitHub credentials and provider secrets. Do not pass package repository tokens or Docker Hub secrets on the command line.'],
			automationNotes: ['Use `--json` to capture selected package metadata, repository credential routing, source-build readiness, Docker Hub readiness for production, and the hosting override command.'],
		},
		helpVisible: true,
		helpFeatured: false,
		executionMode: 'handler',
		handlerName: 'package',
	},
	{
		id: 'market.db',
		name: 'db',
		aliases: [],
		group: 'Utilities',
		summary: 'Manage team TreeDX knowledge-library bindings.',
		description: 'Inspect, provision, connect, mirror, share, publish, bind TreeDX libraries, and plan TreeDX deployment source/image policy.',
		provider: 'default',
		related: ['teams', 'projects', 'capacity'],
		usage: 'treeseed db [status|provision|connect|mirrors|shares|library|topology|publish|image]',
		arguments: [{ name: 'action', description: 'TreeDX action.', required: false }],
		options: [
			{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct API URL.', kind: 'string' },
			{ name: 'team', flags: '--team <team-id>', description: 'Team id for status, provisioning, mirrors, and shares.', kind: 'string' },
			{ name: 'project', flags: '--project <project-id>', description: 'Project id for library binding and topology inspection.', kind: 'string' },
			{ name: 'public', flags: '--public', description: 'Use public federation posture for provisioning or sharing.', kind: 'boolean' },
			{ name: 'selfHosted', flags: '--self-hosted', description: 'Connect a self-hosted TreeDX URL as the primary binding.', kind: 'boolean' },
			{ name: 'url', flags: '--url <url>', description: 'TreeDX base URL for connect/provision.', kind: 'string' },
			{ name: 'registryUrl', flags: '--registry-url <url>', description: 'Optional TreeDX registry URL.', kind: 'string' },
			{ name: 'image', flags: '--image <image-ref>', description: 'TreeDX container image ref, default treeseed/treedx:latest.', kind: 'string' },
			{ name: 'name', flags: '--name <name>', description: 'Mirror display name.', kind: 'string' },
			{ name: 'targetUrl', flags: '--target-url <url>', description: 'Mirror target URL.', kind: 'string' },
			{ name: 'targetKind', flags: '--target-kind <kind>', description: 'Mirror target kind such as git or treedx.', kind: 'string' },
			{ name: 'direction', flags: '--direction <mode>', description: 'Mirror direction: pull, push, or bidirectional.', kind: 'string' },
			{ name: 'scope', flags: '--scope <scope>', description: 'Share scope: team, library, or public_federation.', kind: 'string' },
			{ name: 'targetTeam', flags: '--target-team <team-id>', description: 'Target team id for a team share.', kind: 'string' },
			{ name: 'library', flags: '--library <library-id>', description: 'TreeDX library id for project binding or share.', kind: 'string' },
			{ name: 'instance', flags: '--instance <instance-id>', description: 'TreeDX instance id for project binding.', kind: 'string' },
			{ name: 'repository', flags: '--repository <repo-id>', description: 'TreeDX repository id for project binding.', kind: 'string' },
			{ name: 'contentRepositoryUrl', flags: '--content-repository-url <url>', description: 'Linked GitHub content repository URL.', kind: 'string' },
			{ name: 'environment', flags: '--environment <scope>', description: 'Publish environment for db publish: staging or prod.', kind: 'enum', values: ['staging', 'prod'] },
			{ name: 'branch', flags: '--branch <branch>', description: 'TreeDX branch/ref for source-build planning. Defaults to staging.', kind: 'string' },
			{ name: 'workflow', flags: '--workflow <file>', description: 'TreeDX GitHub Actions workflow file for production image publication.', kind: 'string' },
			{ name: 'syncConfig', flags: '--sync-config', description: 'Sync package image credentials from Treeseed config into the package GitHub environment.', kind: 'boolean' },
			{ name: 'plan', flags: '--plan', description: 'Print the TreeDX image plan without dispatching GitHub Actions.', kind: 'boolean' },
			{ name: 'execute', flags: '--execute', description: 'Dispatch the TreeDX production image workflow when policy allows image publication.', kind: 'boolean' },
			{ name: 'yes', flags: '--yes', description: 'Confirm production db publish.', kind: 'boolean' },
			{ name: 'reason', flags: '--reason <reason>', description: 'Human-readable reason for a content publish.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: [
			'treeseed db status --team team_123',
			'treeseed db provision --team team_123',
			'treeseed db provision --team team_123 --public',
			'treeseed db connect --team team_123 --url https://treedx.example.com --self-hosted',
			'treeseed db mirrors --team team_123 --name customer-copy --target-url https://treedx.customer.example',
			'treeseed db shares --team team_123 --library team/project --public',
			'treeseed db library --project project_123 --library team/project',
			'treeseed db topology --project project_123 --json',
			'treeseed db publish --project project_123 --environment staging',
			'treeseed db image --branch staging --plan --json',
			'treeseed db image --branch main --plan --json',
		],
		help: {
			longSummary: ['TreeDX commands manage the Treeseed control-plane records that bind each team to one primary knowledge-library instance, bind project content to TreeDX libraries, and plan deterministic TreeDX source-build or production image behavior.'],
			whenToUse: ['Use this when provisioning a private TreeDX, attaching a public team to federation, creating mirror/share records, inspecting project content/site/project topology, or publishing the TreeDX image that the API app should reconcile.'],
			beforeYouRun: ['Log in to the selected Treeseed API first for team/project actions. For `db image --execute`, configure GitHub credentials through Treeseed-managed config. Do not pass secrets on the command line; TreeDX credentials belong in host secret managers or encrypted config.'],
			automationNotes: ['Use `--json` for stable TreeDX binding, mirror, share, library, topology, and image policy records. TreeDX, API, operations runner, and agent staging services use source builds. Production image refs are semantic release artifacts.'],
		},
		helpVisible: true,
		helpFeatured: false,
		executionMode: 'handler',
		handlerName: 'db',
	},
	{
		id: 'market.packs',
		name: 'packs',
		aliases: [],
		group: 'Utilities',
		summary: 'Search and download market knowledge packs.',
			description: 'Search knowledge packs and download artifact versions through the integrated market catalog or a selected API.',
		provider: 'default',
		related: ['market', 'template'],
		usage: 'treeseed packs [search|install] [id]',
		arguments: [{ name: 'action', description: 'Packs action.', required: false }],
		options: [
				{ name: 'market', flags: '--market <id-or-url>', description: 'Limit catalog lookup to one configured market id or direct API URL. Without this, search/install uses the integrated catalog from all configured catalog markets.', kind: 'string' },
			{ name: 'version', flags: '--version <version>', description: 'Artifact version for install.', kind: 'string' },
			{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
		],
		examples: ['treeseed packs search', 'treeseed packs install pack_123 --version 1.0.0'],
		help: {
				longSummary: ['Packs searches and downloads knowledge pack artifacts from the integrated catalog formed by central and configured specialized markets.'],
			whenToUse: ['Use this when a project should install a market-published knowledge bundle rather than a local fixture.'],
			beforeYouRun: ['Choose the market and artifact version; private packs require an authenticated market session.'],
			automationNotes: ['Use `--json` to capture artifact metadata and the downloaded file path.'],
		},
		helpVisible: true,
		helpFeatured: false,
		executionMode: 'handler',
		handlerName: 'packs',
	},
	{
		id: 'agents.run',
		name: 'agents',
		aliases: [],
		group: 'Utilities',
		summary: 'Run the Treeseed agent runtime namespace.',
		description: 'Delegate to the `@treeseed/agent` runtime namespace and forward the remaining subcommand arguments.',
		provider: 'default',
		related: ['status', 'config'],
		usage: 'treeseed agents <command>',
		arguments: [{ name: 'command', description: 'Agent subcommand and its remaining arguments.', required: false }],
		examples: ['treeseed agents --help'],
		help: {
			longSummary: [
				'Agents is the CLI entrypoint into the Treeseed agent runtime namespace. It forwards the remaining subcommand arguments to the runtime owned by `@treeseed/agent`.',
			],
			whenToUse: [
				'Use this when the thing you want is inside the agent runtime namespace rather than the main Treeseed command set.',
			],
			beforeYouRun: [
				'Make sure the `@treeseed/agent` runtime is installed and available because this command delegates rather than handling the work locally.',
			],
			outcomes: [
				'Passes control to the agent runtime and forwards the remaining arguments unchanged.',
			],
			examples: [
				example('treeseed agents --help', 'List available agent subcommands', 'Inspect the delegated agent namespace before invoking a specific subcommand.'),
				example('trsd agents --help', 'Use the short alias', 'Reach the same agent namespace through the shorter CLI entrypoint.'),
				example('treeseed agents <command>', 'Delegate a specific agent action', 'Forward an agent subcommand and its arguments to the integrated runtime.'),
			],
			automationNotes: [
				'This command delegates directly to another runtime surface, so downstream semantics come from the agent namespace after the handoff.',
			],
			relatedDetails: [
				related('status', 'Use `status` when you need the main Treeseed workflow state rather than the delegated agent namespace.'),
				related('config', 'Use `config` when agent work depends on missing environment or auth setup.'),
			],
		},
		notes: [
			'Delegates to the `@treeseed/agent` runtime.',
			'Use `treeseed agents --help` to list supported agent subcommands.',
		],
		helpVisible: true,
		helpFeatured: false,
		executionMode: 'delegate',
		delegateTo: 'agents',
	},
];
