import { randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { parse as parseYaml } from 'yaml';
import type { CommandContext,ParsedInvocation } from '../../../types.js';
import { createMarketClientForInvocation } from '../../content/market-utils.js';
import { fail,guidedResult } from '../../utilities/utils.js';
import { capacityStringArg as text } from '../capacity-core/capacity-command-arguments.js';
import { resolveCapacityTeam } from '../capacity-core/capacity-market-context.js';

export const CAPACITY_AGENT_DEPLOYMENT_ACTIONS=new Set(['agent-deploy','agent-deployment','agent-deployment-activate','agent-deployment-upgrade']);
function values(invocation:ParsedInvocation,key:string){const value=invocation.args[key];return (Array.isArray(value)?value:[value]).flatMap((entry)=>typeof entry==='string'?entry.split(','):[]).map((entry)=>entry.trim()).filter(Boolean);}
async function document(invocation:ParsedInvocation,context:CommandContext){const file=text(invocation,'file');const inline=text(invocation,'document');if(!file&&!inline)return {};const parsed=parseYaml(inline??await readFile(resolve(context.cwd,file!),'utf8'));if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))throw new Error('Deployment document must be a YAML or JSON object.');return parsed as Record<string,unknown>;}

export async function runCapacityAgentDeployment(action:string,invocation:ParsedInvocation,context:CommandContext){
	const teamSelector=text(invocation,'team');if(!teamSelector)return fail(`Missing --team for capacity ${action}.`);const {client}=createMarketClientForInvocation(invocation,context,{requireAuth:true,allowLocalAcceptanceAdmin:true});const team=await resolveCapacityTeam(client,teamSelector);const deploymentId=text(invocation,'deployment');
	if(action==='agent-deployment'){if(!deploymentId)return fail('Missing --deployment for capacity agent-deployment.');const payload=await client.agentDeployment(team.teamId,deploymentId);return guidedResult({command:`capacity ${action}`,summary:`Inspected deployment ${deploymentId}.`,report:{action,payload}});}
	const plan=invocation.args.plan===true;const execute=invocation.args.execute===true;if(plan===execute)return fail(`Capacity ${action} is mutating. Choose exactly one of --plan or --execute.`);const input=await document(invocation,context);const key=text(invocation,'idempotencyKey')??`cli:${action}:${randomUUID()}`;
	if(action==='agent-deployment-activate'){if(!deploymentId)return fail('Missing --deployment for capacity agent-deployment-activate.');if(!execute)return guidedResult({command:`capacity ${action}`,summary:'Deployment activation plan prepared.',report:{action,deploymentId,mode:'plan',prerequisiteEvidence:input.prerequisiteEvidence??[]}});const payload=await client.activateAgentDeployment(team.teamId,deploymentId,{idempotencyKey:key,prerequisiteEvidence:Array.isArray(input.prerequisiteEvidence)?input.prerequisiteEvidence as Array<{id:string;passed:boolean;evidenceRef:string}>:[]});return guidedResult({command:`capacity ${action}`,summary:`Activated deployment ${deploymentId}.`,report:{action,payload}});}
	if(action==='agent-deployment-upgrade'){if(!deploymentId)return fail('Missing --deployment for capacity agent-deployment-upgrade.');const sourceRef=text(invocation,'sourceRef');if(!sourceRef)return fail('Missing --source-ref for capacity agent-deployment-upgrade.');const payload=await client.upgradeAgentDeployment(team.teamId,deploymentId,{sourceRef,execute,idempotencyKey:execute?key:undefined,generation:text(invocation,'generation')??undefined});return guidedResult({command:`capacity ${action}`,summary:`${execute?'Executed':'Planned'} deployment upgrade ${deploymentId}.`,report:{action,payload}});}
	const sourceProjectId=text(invocation,'sourceProject');const targetProjectIds=values(invocation,'targetProject');const agentId=text(invocation,'agent');const groupId=text(invocation,'group');if(!sourceProjectId||!targetProjectIds.length)return fail('agent-deploy requires --source-project and at least one --target-project.');if(Boolean(agentId)===Boolean(groupId))return fail('agent-deploy requires exactly one of --agent or --group.');const results=[];for(const targetProjectId of targetProjectIds){const request={sourceProjectId,targetProjectId,sourceRef:text(invocation,'sourceRef')??undefined,agentId:agentId??undefined,groupId:groupId??undefined,bindings:(input.bindings??input) as Record<string,never>,generation:text(invocation,'generation')??undefined,idempotencyKey:`${key}:${targetProjectId}`};try{results.push({targetProjectId,ok:true,payload:plan?await client.planAgentDeployment(team.teamId,request):await client.executeAgentDeployment(team.teamId,{...request,idempotencyKey:request.idempotencyKey})});}catch(error){results.push({targetProjectId,ok:false,error:error instanceof Error?error.message:String(error)});}}
	const blocked=results.filter((entry)=>!entry.ok);return guidedResult({command:`capacity ${action}`,summary:`${plan?'Planned':'Executed'} ${results.length} governed agent deployment target${results.length===1?'':'s'}${blocked.length?` with ${blocked.length} blocked`:''}.`,exitCode:blocked.length?1:0,report:{action,mode:plan?'plan':'live',results}});
}
