import { parseCommunicationAddresses } from '@treeseed/sdk/operator-contracts';

type Row=Record<string,any>;
export type ChatLine={key:string;heading:string;body:string;kind:'message'|'response'|'notice'|'error';occurredAt?:string;actorHandle?:string|null};
const record=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:{};
const textValue=(value:unknown)=>typeof value==='string'?value:'';
const clock=(value:string)=>{const date=new Date(value);return Number.isFinite(date.getTime())?date.toLocaleTimeString():value;};

export function requiredCommunicationAddresses(message:string){return parseCommunicationAddresses(message).filter(address=>address.requirement==='required').map(address=>address.address);}
export function prepareInteractiveMessage(message:string,selected:string[]){const explicit=requiredCommunicationAddresses(message),recipients=[...new Set([...selected,...explicit])];if(!recipients.length)throw Object.assign(new Error('The first interactive message must begin with at least one agent address or select agents in the sidebar.'),{category:'invalid_input',code:'communication_recipient_required'});const missing=selected.filter(address=>!explicit.includes(address));return{recipients,message:missing.length?`${missing.join(' ')}\n\n${message}`:message};}
export function nextInteractiveRecipients(message:string,current:string[]){return prepareInteractiveMessage(message,current).recipients;}
export function eventLine(event:Row,diagnostics:boolean):ChatLine|null{const type=textValue(event.type),actor=record(event.actor),payload=record(event.payload),occurredAt=textValue(event.occurredAt),time=clock(occurredAt),handle=textValue(actor.handle)||textValue(actor.id);if(type==='message.posted')return{key:textValue(event.id),heading:`you   ${time}`,body:textValue(payload.markdown)||textValue(event.summary),kind:'message',occurredAt,actorHandle:null};if(type==='agent.response')return{key:textValue(event.id),heading:`${handle}   ${time}`,body:textValue(payload.markdown)||textValue(event.summary),kind:'response',occurredAt,actorHandle:handle};if(['agent.abstained','agent.failed','mention.acknowledged','response_lease.accepted'].includes(type))return{key:textValue(event.id),heading:`${type}   ${time}`,body:textValue(event.summary),kind:type==='agent.failed'?'error':'notice',occurredAt,actorHandle:handle};if(diagnostics&&type==='agent.progress')return{key:textValue(event.id),heading:`progress   ${time}`,body:textValue(event.summary),kind:'notice',occurredAt,actorHandle:handle};return null;}
export function chatTranscriptMarkdown(topic:string,lines:ChatLine[],listeners:string[],exportedAt=new Date().toISOString()){return [`# TreeSeed Discussion: ${topic}`,'',`Exported: ${exportedAt}`,`Listeners: ${listeners.join(', ')||'none'}`,'',...lines.flatMap(line=>[`## ${line.heading}`,'',line.kind==='notice'?`> ${line.body.replace(/\n/gu,'\n> ')}`:line.body,'','---',''])].join('\n');}
export function renderInteractiveChat(input:{channel:string;recipients:string[];lines:ChatLine[];composer:string;status:string;diagnostics:boolean;scroll:number},width:number,height:number){const separator='═'.repeat(Math.max(1,width)),composer=input.composer.split('\n');return [`TreeSeed topic: ${input.channel||'select a topic'}`,separator,...input.lines.flatMap(line=>[line.heading,'',line.body,'',separator]),input.status,'─'.repeat(Math.max(1,width)),`› ${composer[0]??''}`,...composer.slice(1).map(line=>`  ${line}`)].slice(-Math.max(1,height)).join('\n');}
