import type { OperationSpec } from '../operations/operations-types.ts';

export const serviceOperationSpecs: OperationSpec[] = [{
	id: 'market.services',
	name: 'services',
	group: 'Utilities',
	summary: 'Inspect team provider services, capability bindings, encrypted envelopes, and operation leases.',
	description: 'Reads the provider-first service control plane without accepting provider credentials or passphrases as command arguments.',
	provider: 'default',
	related: ['teams', 'projects', 'capacity'],
	usage: 'treeseed services <providers|list|show|authorities|repository|workflows|workflow-run|envelopes|import-envelopes|lease> [options] [--json]',
	arguments: [{ name: 'action', description: 'Read-only service-management action.', required: false }],
	options: [
		{ name: 'market', flags: '--market <id-or-url>', description: 'Configured Market profile or API URL.', kind: 'string' },
		{ name: 'team', flags: '--team <team-id>', description: 'Team whose service metadata is inspected.', kind: 'string' },
		{ name: 'connection', flags: '--connection <connection-id>', description: 'Provider connection identifier.', kind: 'string' },
		{ name: 'project', flags: '--project <project-id>', description: 'Project whose repository or workflow bindings are inspected.', kind: 'string' },
		{ name: 'run', flags: '--run <workflow-run-id>', description: 'Correlated remote workflow run identifier.', kind: 'string' },
		{ name: 'lease', flags: '--lease <lease-id>', description: 'Secret operation lease identifier.', kind: 'string' },
		{ name: 'file', flags: '--file <encrypted-envelope-json>', description: 'Encrypted envelope export to import without decryption.', kind: 'string' },
		{ name: 'json', flags: '--json', description: 'Emit stable machine-readable output.', kind: 'boolean' },
	],
	examples: [
		'treeseed services providers --market local --json',
		'treeseed services list --market local --team team_123 --json',
		'treeseed services show --market local --team team_123 --connection connection_123 --json',
		'treeseed services authorities --market local --team team_123 --connection connection_123 --json',
		'treeseed services repository --market local --team team_123 --project project_123 --json',
		'treeseed services workflows --market local --team team_123 --project project_123 --json',
		'treeseed services workflow-run --market local --team team_123 --run run_123 --json',
		'treeseed services envelopes --market local --team team_123 --connection connection_123 --json',
		'treeseed services import-envelopes --market local --team team_123 --connection connection_123 --file encrypted-envelopes.json --json',
	],
	notes: [
		'Passphrases and plaintext provider credentials are never accepted as flags.',
		'Envelope output is encrypted and remains bound to its original team, connection, profile, field, and key version.',
	],
	help: {
		longSummary: ['Services exposes read-only provider connection, repository authority, workflow, envelope, and lease evidence.'],
		whenToUse: ['Use it to diagnose configured service capabilities and operation custody without reading plaintext credentials.'],
		beforeYouRun: ['Authenticate to the selected market and provide the owning team for team-scoped service records.'],
		automationNotes: ['Output is bounded and encrypted where applicable; passphrases and plaintext provider credentials are never accepted as flags.'],
	},
	helpVisible: true,
	helpFeatured: false,
	executionMode: 'handler',
	handlerName: 'services',
}];
