import type { OperationSpec } from '../../operations/operations-types.ts';

export const governanceOperationSpecs: OperationSpec[] = [{
	id: 'market.governance',
	name: 'governance',
	aliases: [],
	group: 'Utilities',
	summary: 'Inspect and operate project proposals and decisions through the authenticated control plane.',
	description: 'Provides the CLI human and AI-operated human cockpit for proposal discussion, voting, evaluation, and decision inspection.',
	provider: 'default',
	related: ['projects', 'capacity'],
	usage: 'treeseed governance <action> --project <project-id> [options] [--json]',
	arguments: [{ name: 'action', description: 'Proposal or decision action.', required: true }],
	options: [
		{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or API URL.', kind: 'string' },
		{ name: 'project', flags: '--project <project-id>', description: 'Project containing the proposal or decision.', kind: 'string' },
		{ name: 'proposal', flags: '--proposal <proposal-id>', description: 'Proposal identifier.', kind: 'string' },
		{ name: 'decision', flags: '--decision <decision-id>', description: 'Decision identifier.', kind: 'string' },
		{ name: 'title', flags: '--title <text>', description: 'Proposal title.', kind: 'string' },
		{ name: 'summary', flags: '--summary <text>', description: 'Proposal summary.', kind: 'string' },
		{ name: 'body', flags: '--body <text>', description: 'Proposal body.', kind: 'string' },
		{ name: 'file', flags: '--file <path>', description: 'YAML or JSON proposal document path.', kind: 'string' },
		{ name: 'document', flags: '--document <yaml-or-json>', description: 'Inline YAML or JSON proposal document.', kind: 'string' },
		{ name: 'proposalType', flags: '--proposal-type <type>', description: 'Proposal classification.', kind: 'string' },
		{ name: 'changeReason', flags: '--change-reason <text>', description: 'Required summary for an immutable proposal revision.', kind: 'string' },
		{ name: 'kind', flags: '--kind <question|concern|support|response>', description: 'Discussion contribution kind.', kind: 'enum', values: ['question', 'concern', 'support', 'response'] },
		{ name: 'message', flags: '--message <text>', description: 'Discussion message.', kind: 'string' },
		{ name: 'contributor', flags: '--contributor <content-ref>', description: 'Verified person or agent content reference required when asking a TreeDX-backed question.', kind: 'string' },
		{ name: 'vote', flags: '--vote <support|object|abstain>', description: 'Governance vote.', kind: 'enum', values: ['support', 'object', 'abstain'] },
		{ name: 'status', flags: '--status <status>', description: 'Status filter or administrative decision.', kind: 'string' },
		{ name: 'reason', flags: '--reason <text>', description: 'Evidence-based reason for the action.', kind: 'string' },
		{ name: 'limit', flags: '--limit <count>', description: 'Maximum records to return.', kind: 'string' },
		{ name: 'idempotencyKey', flags: '--idempotency-key <key>', description: 'Stable mutation idempotency key.', kind: 'string' },
		{ name: 'simulateHuman', flags: '--simulate-human', description: 'Record that an AI operator is acting through an authenticated human authority.', kind: 'boolean' },
		{ name: 'simulationPurpose', flags: '--simulation-purpose <text>', description: 'Purpose of the human-simulation exercise.', kind: 'string' },
		{ name: 'workday', flags: '--workday <workday-id>', description: 'Active workday associated with the simulated action.', kind: 'string' },
		{ name: 'assignment', flags: '--assignment <assignment-id>', description: 'Optional assignment associated with the simulated action.', kind: 'string' },
		{ name: 'production', flags: '--production', description: 'Request production authority; does not bypass deployment suspension.', kind: 'boolean' },
		{ name: 'yes', flags: '--yes', description: 'Confirm a binding vote or decision.', kind: 'boolean' },
		{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON.', kind: 'boolean' },
	],
	examples: [
		'treeseed governance proposal-list --project project_123 --json',
		'treeseed governance proposal-discuss --project project_123 --proposal proposal_123 --kind question --message "What evidence supports this?" --simulate-human --workday workday_123 --reason "Verify the proposal before voting." --json',
		'treeseed governance proposal-vote --project project_123 --proposal proposal_123 --vote support --simulate-human --workday workday_123 --reason "Independent reviews passed." --yes --json',
	],
	help: {
		longSummary: ['Governance exposes project proposal and decision operations without bypassing authenticated API policy.'],
		whenToUse: ['Use it to inspect, discuss, vote on, evaluate, or administratively decide project proposals during a workday.'],
		beforeYouRun: ['Authenticate to the selected market. Simulated-human decisions require an active workday, a reason, and confirmation.'],
		automationNotes: ['Every mutation sends an idempotency key. Simulation provenance never grants permissions and production release remains suspended.'],
	},
	helpVisible: true,
	helpFeatured: false,
	executionMode: 'handler',
	handlerName: 'governance',
}];
