import type { OperationSpec } from '../operations/operations-types.ts';

export const authOperationSpecs: OperationSpec[] = [{
	id: 'auth.login',
	name: 'auth',
	aliases: [],
	group: 'Utilities',
	provider: 'default',
	related: [],
	summary: 'Register, recover, sign in, and inspect TreeSeed identities without requiring a web UI.',
	description: 'Provides a UI-independent human account lifecycle and keeps device login as an explicit compatibility mode.',
	usage: 'trsd auth <register|confirm-email|login|password-reset|whoami|logout> [options]',
	arguments: [
		{ name: 'action', description: 'Authentication action.', required: true },
		{ name: 'subcommand', description: 'Nested action, such as password-reset request or complete.', required: false },
	],
	options: [
		{ name: 'market', flags: '--market <id-or-url>', description: 'Select a configured market id or direct local API URL.', kind: 'string' },
		{ name: 'host', flags: '--host <id>', description: 'Compatibility alias for the configured host id.', kind: 'string' },
		{ name: 'email', flags: '--email <address>', description: 'Human account email address. This value is not a secret.', kind: 'string' },
		{ name: 'username', flags: '--username <name>', description: 'Public TreeSeed username.', kind: 'string' },
		{ name: 'name', flags: '--name <display-name>', description: 'Human display name.', kind: 'string' },
		{ name: 'login', flags: '--login <email-or-username>', description: 'Email address or username for password sign-in.', kind: 'string' },
		{ name: 'device', flags: '--device', description: 'Use the legacy browser/device approval flow instead of password sign-in.', kind: 'boolean' },
		{ name: 'allMarkets', flags: '--all-markets', description: 'Show stored identities for all configured markets.', kind: 'boolean' },
		{ name: 'json', flags: '--json', description: 'Emit machine-readable non-secret output. Secret-taking actions require an interactive TTY.', kind: 'boolean' },
	],
	examples: [
		'trsd auth register --market local --email person@example.test --username person --name "Person Name"',
		'trsd auth confirm-email --market local',
		'trsd auth login --market local --login person@example.test',
		'trsd auth password-reset request --market local --email person@example.test',
		'trsd auth password-reset complete --market local',
		'trsd auth whoami --market local',
	],
	help: {
		longSummary: ['Human accounts can be created, confirmed, recovered, and used entirely through the CLI and local API.'],
		whenToUse: ['Use this command tree when a human needs to register, confirm, recover, sign in, inspect, or end a TreeSeed account session without relying on the web UI.'],
		beforeYouRun: ['Use an interactive terminal for passwords and confirmation or recovery tokens. They are never accepted as options.'],
		automationNotes: ['Agent automation must use a scoped service principal instead of a human password session.'],
		warnings: ['Never paste a password, confirmation token, recovery token, session cookie, or access token into chat or a command argument.'],
	},
	helpVisible: true,
	helpFeatured: false,
	executionMode: 'handler',
	handlerName: 'auth',
}];
