import type { OperationSpec } from '../operations/operations-types.ts';
import {
	devManagedHelpCommand, example, related, workspaceCommand,
	DEV_LOGS_OPTIONS, DEV_RUNTIME_OPTIONS, DEV_START_OPTIONS, DEV_STATUS_OPTIONS, DEV_STOP_OPTIONS,
	PASS_THROUGH_ARGS, TOOL_WRAPPER_OPTIONS,
} from '../operations/operations-registry-support.ts';

export const hostingAndReconciliationOperationSpecs: OperationSpec[] = [
	{
				id: 'audit.hosting',
				name: 'audit',
			aliases: [],
			group: 'Validation',
			summary: 'Audit TreeSeed hosting readiness.',
			description: 'Run a read-only or explicit repair audit for Repository, Web, Processing, and Email hosting setup.',
			provider: 'default',
			related: ['status', 'config', 'save', 'release'],
			usage: 'treeseed audit hosting [--environment current|local|staging|prod] [--repair] [--live] [--json]',
			arguments: [{ name: 'target', description: 'Audit target. Use hosting.', required: false }],
			options: [
				{ name: 'environment', flags: '--environment <environment>', description: 'Audit environment. Defaults to current branch mapping.', kind: 'enum', values: ['current', 'local', 'staging', 'prod'] },
				{ name: 'repair', flags: '--repair', description: 'Explicitly reconcile missing platform/provider resources.', kind: 'boolean' },
				{ name: 'live', flags: '--live', description: 'Collect live Railway and HTTP observations for hosted service checks.', kind: 'boolean' },
				{ name: 'hostKinds', flags: '--host-kinds <kinds>', description: 'Comma-separated host kinds to audit.', kind: 'string' },
				{ name: 'json', flags: '--json', description: 'Emit the hosting audit report as JSON.', kind: 'boolean' },
			],
			examples: ['treeseed audit hosting', 'treeseed audit hosting --environment staging --json', 'treeseed audit hosting --repair --environment prod'],
			help: {
				workflowPosition: 'validate',
				longSummary: [
					'The hosting audit proves that TreeSeed can use its configured Repository, Web, Processing, and Email platforms before saving hosts or launching team projects.',
					'It is read-only by default. Use `--repair` only when you explicitly want TreeSeed to reconcile provider resources.',
				],
				whenToUse: [
					'Run this before saving managed hosts, launching a hub, or promoting a release that depends on hosted provider resources.',
					'Use it after changing provider credentials or service topology to verify that the selected environment is complete.',
				],
				beforeYouRun: [
					'Run from the TreeSeed workspace you want to audit.',
					'Use `--json` for automation and `--repair` only for deliberate provider reconciliation.',
				],
				automationNotes: [
					'The report lists missing key names and resource identifiers but never prints decrypted secret values.',
					'Save, stage, and release resource verification can include the same read-only audit; repair remains explicit.',
				],
			},
			helpVisible: true,
			helpFeatured: true,
			executionMode: 'handler',
			handlerName: 'audit',
		},
	{
			id: 'hosting',
			name: 'hosting',
			aliases: [],
			group: 'Utilities',
			summary: 'Plan, apply, verify, and inspect the Treeseed hosting graph.',
			description: 'Resolve host-agnostic service types into environment-specific host bindings for local dev, staging, and production.',
			provider: 'default',
			related: ['status', 'dev', 'config', 'stage', 'release'],
			usage: 'treeseed hosting [status|plan|apply|verify|destroy] [--environment local|staging|prod] [--app web|api] [--service api] [--placement-only] [--replace-pending-volumes --yes] [--json]',
			arguments: [{ name: 'action', description: 'Hosting action.', required: false }],
			options: [
				{ name: 'environment', flags: '--environment <scope>', description: 'Hosting environment to resolve.', kind: 'enum', values: ['local', 'staging', 'prod'] },
				{ name: 'app', flags: '--app <app-id>', description: 'Limit hosting graph work to one discovered Treeseed application, such as web or api.', kind: 'string' },
				{ name: 'service', flags: '--service <service-id>', description: 'Limit hosting graph work to one service id. Repeat or comma-separate for multiple services.', kind: 'string' },
				{ name: 'placement', flags: '--placement <placement>', description: 'Limit hosting graph work to one service placement.', kind: 'string' },
				{ name: 'host', flags: '--host <host-id>', description: 'Limit hosting graph work to one host id.', kind: 'string' },
				{ name: 'live', flags: '--live', description: 'Request live provider verification where supported.', kind: 'boolean' },
				{ name: 'placementOnly', flags: '--placement-only', description: 'Limit hosting plan output to deterministic placement compilation without provider-state reconciliation.', kind: 'boolean' },
				{ name: 'replacePendingVolumes', flags: '--replace-pending-volumes', description: 'Allow hosting apply to replace Railway volumes already queued for deletion. Permanently discards their data and requires --yes.', kind: 'boolean' },
				{ name: 'yes', flags: '--yes', description: 'Confirm an explicitly destructive hosting operation.', kind: 'boolean' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: [
				'treeseed hosting status --environment local',
				'treeseed hosting plan --environment staging --json',
				'treeseed hosting plan --environment staging --app web --json',
				'treeseed hosting plan --environment staging --app api --json',
				'treeseed hosting plan --environment staging --service api --json',
				'treeseed hosting verify --environment prod --json',
				'treeseed hosting apply --environment staging --app api --json',
				'treeseed hosting destroy --environment staging --app api --json',
			],
			help: {
				longSummary: ['Hosting resolves Treeseed application profiles into service placements, service types, host capabilities, and provider/local resources.'],
				whenToUse: ['Use this before dev, stage, or release when you need to inspect host bindings, missing capabilities, or TreeDX/public federation placement.'],
				beforeYouRun: ['Run from the Treeseed workspace. Use `--json` for automation. `plan` is non-mutating; `apply`, `verify --live`, and `destroy` operate on real hosted resources.'],
				automationNotes: ['The JSON report includes placements, units, selected hosts, required capabilities, project groups, and verification checks without secret values.'],
			},
			helpVisible: true,
			helpFeatured: true,
			executionMode: 'handler',
			handlerName: 'hosting',
		},
	{
			id: 'reconcile',
			name: 'reconcile',
			aliases: [],
			group: 'Utilities',
			summary: 'Run canonical reconciliation platform diagnostics.',
			description: 'Plan, apply, verify, destroy, and live-test SDK-owned exact-state reconciliation.',
			provider: 'default',
			related: ['hosting', 'config', 'stage', 'release'],
			usage: 'treeseed reconcile [plan|status|verify|apply|destroy|test-live] [--environment local|staging|prod] [--unit-id <id>] [--execute] [--json]',
			arguments: [{ name: 'action', description: 'Reconcile action.', required: false }],
			options: [
				{ name: 'provider', flags: '--provider <provider>', description: 'Provider live-test scope. Use railway, cloudflare, github, local, or all.', kind: 'string' },
				{ name: 'mode', flags: '--mode <mode>', description: 'Live-test mode. Smoke is read-only; acceptance and cleanup mutate isolated provider resources and require --yes.', kind: 'enum', values: ['smoke', 'acceptance', 'cleanup'] },
				{ name: 'environment', flags: '--environment <scope>', description: 'Environment to test.', kind: 'enum', values: ['local', 'staging', 'prod'] },
				{ name: 'unitId', flags: '--unit-id <id>', description: 'Limit plan/apply/verify/destroy to one or more comma-separated desired unit ids.', kind: 'string' },
				{ name: 'unitType', flags: '--unit-type <type>', description: 'Limit plan/apply/verify/destroy to one or more desired unit types.', kind: 'string' },
				{ name: 'resourceKind', flags: '--resource-kind <kind>', description: 'Limit plan/apply/verify/destroy to one or more desired resource kinds.', kind: 'string' },
				{ name: 'packageId', flags: '--package-id <id>', description: 'Limit plan/apply/verify/destroy to one or more Treeseed package ids.', kind: 'string' },
				{ name: 'serviceId', flags: '--service-id <id>', description: 'Limit plan/apply/verify/destroy to one or more service ids.', kind: 'string' },
				{ name: 'serviceType', flags: '--service-type <type>', description: 'Limit plan/apply/verify/destroy to one or more service unit types.', kind: 'string' },
				{ name: 'execute', flags: '--execute', description: 'Allow reconcile apply or destroy to mutate provider resources.', kind: 'boolean' },
				{ name: 'yes', flags: '--yes', description: 'Confirm acceptance or cleanup mode may create and delete real isolated provider resources.', kind: 'boolean' },
				{ name: 'json', flags: '--json', description: 'Emit machine-readable JSON instead of human-readable text.', kind: 'boolean' },
			],
			examples: [
				'treeseed reconcile plan --environment staging --json',
				'treeseed reconcile verify --environment staging --json',
				'treeseed reconcile apply --environment staging --json',
				'treeseed reconcile apply --environment staging --unit-id github-secret-binding:root:staging:TREESEED_CREDENTIAL_SESSION_SECRET --execute --json',
				'treeseed reconcile apply --environment staging --execute --json',
				'treeseed reconcile test-live --provider local --json',
				'treeseed reconcile test-live --provider railway --environment staging --json',
				'treeseed reconcile test-live --provider all --environment staging --json',
				'treeseed reconcile test-live --mode acceptance --provider railway --environment staging --yes --json',
				'treeseed reconcile test-live --mode cleanup --provider all --environment staging --yes --json',
			],
			help: {
				longSummary: ['Reconcile is the canonical SDK lifecycle for provider state: refresh, diff, plan, validate, apply, refresh, verify, and persist. Smoke mode is fast and read-only. Acceptance mode creates, updates, verifies, and destroys isolated resources. Cleanup mode removes leftover isolated live-test resources. Missing provider coverage is reported as blocking drift, not skipped success.'],
				whenToUse: ['Use this before staging or release promotions when provider tokens are configured, or when adding a new provider/resource adapter.'],
				beforeYouRun: ['Run from the Treeseed workspace. Provider tests use encrypted Treeseed config values and deterministic isolated prefixes.'],
				automationNotes: ['The JSON report contains the desired resource graph, package units, reconcile actions, postconditions, blocked drift, provider limitations, live verification, and ok state.'],
			},
			helpVisible: true,
			helpFeatured: false,
			executionMode: 'handler',
			handlerName: 'reconcile',
		},
];
