import { createAgentGuaranteeCatalogStatus } from '@treeseed/sdk/guarantees';
import { appendFileSync,existsSync,mkdirSync,readFileSync,writeFileSync } from 'node:fs';
import { isAbsolute,relative,resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import type { CommandContext,ParsedInvocation } from '../../types.js';

type Row=Record<string,unknown>;
const record=(value:unknown):Row=>value&&typeof value==='object'&&!Array.isArray(value)?value as Row:{};
const records=(value:unknown)=>Array.isArray(value)?value.map(record):[];
const text=(value:unknown)=>typeof value==='string'?value.trim():'';
const arg=(invocation:ParsedInvocation,key:string)=>text(invocation.args[key]);
const safePath=(context:CommandContext,value:string)=>{if(!value||isAbsolute(value))return null;const path=resolve(context.cwd,value);const rel=relative(context.cwd,path);return rel.startsWith('..')||isAbsolute(rel)?null:path;};
const allowed=new Set(['capacity','guarantees','dev','ready','scene']);
function sanitized(args:string[]){return args.map((value,index)=>index>0&&/token|secret|credential|password|key/iu.test(args[index-1]??'')?'[REDACTED]':value);}
function diagnostic(value:string){return value.replace(/(?:bearer\s+)?[A-Za-z0-9_-]{24,}\.[A-Za-z0-9_-]{16,}(?:\.[A-Za-z0-9_-]{16,})?/giu,'[REDACTED]').slice(-4000);}
export function campaignEvidenceReport(value:unknown,key=''):unknown{if(['content','body','files','results','queryResult','queryResults'].includes(key))return '[OMITTED_NON_EVIDENCE_PAYLOAD]';if(Array.isArray(value))return value.map((entry)=>campaignEvidenceReport(entry,key));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value as Row).map(([name,entry])=>[name,campaignEvidenceReport(entry,name)]));return value;}
function event(root:string,entry:Row){appendFileSync(resolve(root,'journal.jsonl'),`${JSON.stringify({schemaVersion:'treeseed.agent-guarantee-campaign-event/v1',observedAt:new Date().toISOString(),...entry})}\n`,{mode:0o600});}
function command(input:Row,variables:Row={}){const args=Array.isArray(input.args)?input.args.map(String).map((value)=>value.replace(/\{\{([a-zA-Z0-9_.-]+)\}\}/gu,(_,key)=>{const replacement=variables[key];if(typeof replacement!=='string'||!replacement)throw new Error(`Campaign variable ${key} is unresolved.`);return replacement;})):[];if(!args.length||!allowed.has(args[0]))throw new Error(`Campaign command must begin with one of: ${[...allowed].join(', ')}.`);return args.includes('--json')?args:[...args,'--json'];}
function at(value:unknown,path:string){return path.split('.').filter(Boolean).reduce<unknown>((current,key)=>record(current)[key],value);}
function run(context:CommandContext,root:string,variant:string,input:Row,variables:Row={}){const args=command(input,variables);const startedAt=new Date().toISOString();const result=spawnSync(resolve(context.cwd,'node_modules/.bin/trsd'),args,{cwd:context.cwd,env:context.env,encoding:'utf8',timeout:Math.max(1,Number(input.timeoutSeconds??1200))*1000,maxBuffer:8*1024*1024});let report:unknown=null;try{report=JSON.parse(result.stdout||'null');}catch{}const entry={type:'command',variant,args:sanitized(args),startedAt,completedAt:new Date().toISOString(),exitCode:result.status,signal:result.signal,report:campaignEvidenceReport(report),stderr:diagnostic(result.stderr||'')};event(root,entry);if(result.status!==0)throw new Error(`Campaign command failed (${args.slice(0,3).join(' ')}): ${diagnostic(result.stderr||result.stdout||'unknown failure').slice(-1000)}`);for(const [name,path]of Object.entries(record(input.capture))){const value=at(report,String(path));const captured=typeof value==='string'?value:Array.isArray(value)&&value.length===1&&typeof value[0]==='string'?value[0]:null;if(!captured)throw new Error(`Campaign capture ${name} did not resolve one exact identity at ${String(path)}.`);variables[name]=captured;}return entry;}
export function requiredCampaignCommands(variant:Row){const names=records(variant.commands).map((entry)=>(Array.isArray(entry.args)?entry.args.map(String):[]).slice(0,2).join(' '));const required=['guarantees watch','capacity assignment-artifacts-verify','capacity workday-close-admission','guarantees proof-capture'];if(text(variant.id)==='interruption-resume')required.push('capacity down','capacity up');return required.filter((name)=>!names.includes(name));}

export function handleAgentCampaignRun(invocation:ParsedInvocation,context:CommandContext){
	const file=safePath(context,arg(invocation,'file'));if(!file||!existsSync(file))return {exitCode:1,stdout:[],stderr:['campaign-run requires an existing workspace-relative --file.'],report:{command:'guarantees campaign-run',ok:false}};
	let manifest:Row;try{manifest=JSON.parse(readFileSync(file,'utf8')) as Row;}catch(error){return {exitCode:1,stdout:[],stderr:[error instanceof Error?error.message:String(error)],report:{command:'guarantees campaign-run',ok:false}};}
	const id=text(manifest.id);const catalog=createAgentGuaranteeCatalogStatus({workspaceRoot:context.cwd,catalog:'agent.system'});const generation=text(manifest.generation)||catalog.generation;
	if(!id||generation!==catalog.generation)return {exitCode:1,stdout:[],stderr:['Campaign id is required and its generation must equal the current canonical generation.'],report:{command:'guarantees campaign-run',ok:false,generation:catalog.generation}};
	const variants=records(manifest.variants);const ids=variants.map((entry)=>text(entry.id));if(JSON.stringify(ids)!==JSON.stringify(['baseline','clean-repeat','interruption-resume']))return {exitCode:1,stdout:[],stderr:['Campaign variants must be baseline, clean-repeat, interruption-resume in that order.'],report:{command:'guarantees campaign-run',ok:false}};const missing=variants.flatMap((variant)=>requiredCampaignCommands(variant).map((name)=>`${text(variant.id)}:${name}`));if(missing.length)return {exitCode:1,stdout:[],stderr:[`Campaign variants omit required lifecycle commands: ${missing.join(', ')}.`],report:{command:'guarantees campaign-run',ok:false}};
	const root=resolve(context.cwd,'.treeseed/guarantees/campaigns',generation,id);mkdirSync(root,{recursive:true});writeFileSync(resolve(root,'manifest.json'),`${JSON.stringify(manifest,null,2)}\n`,{mode:0o600});
	if(invocation.args.execute!==true)return {exitCode:0,stdout:['Campaign plan validated; execution was not requested.'],stderr:[],report:{command:'guarantees campaign-run',ok:true,mode:'plan',id,generation,variants:ids,root:relative(context.cwd,root)}};
	const variables:Row={generation};let currentVariant='campaign';const journalCleanup=()=>{for(const entry of records(manifest.cleanup)){try{const resolved={...entry,args:command(entry,variables)};appendFileSync(resolve(root,'cleanup-journal.jsonl'),`${JSON.stringify({variant:currentVariant,...resolved})}\n`,{mode:0o600});}catch{}}};
	try{for(const variant of variants){currentVariant=text(variant.id);event(root,{type:'variant-started',variant:variant.id});run(context,root,currentVariant,{args:['guarantees','preflight']},variables);for(const entry of records(variant.commands))run(context,root,currentVariant,entry,variables);journalCleanup();for(const entry of records(manifest.cleanup))run(context,root,currentVariant,entry,variables);event(root,{type:'variant-completed',variant:variant.id});}return {exitCode:0,stdout:['All three campaign variants completed through argument-array TreeSeed commands.'],stderr:[],report:{command:'guarantees campaign-run',ok:true,id,generation,root:relative(context.cwd,root)}};}catch(error){journalCleanup();event(root,{type:'campaign-blocked',error:error instanceof Error?error.message:String(error)});return {exitCode:1,stdout:[],stderr:[error instanceof Error?error.message:String(error)],report:{command:'guarantees campaign-run',ok:false,id,generation,root:relative(context.cwd,root)}};}
}

export function handleAgentCampaignCleanup(invocation:ParsedInvocation,context:CommandContext){const id=arg(invocation,'campaign');const generation=createAgentGuaranteeCatalogStatus({workspaceRoot:context.cwd,catalog:'agent.system'}).generation;const root=resolve(context.cwd,'.treeseed/guarantees/campaigns',generation,id);const journal=resolve(root,'cleanup-journal.jsonl');if(!id||!existsSync(journal))return {exitCode:1,stdout:[],stderr:['campaign-cleanup requires an exact campaign with a resolved cleanup journal in the current generation.'],report:{command:'guarantees campaign-cleanup',ok:false}};const entries=readFileSync(journal,'utf8').split(/\r?\n/u).filter(Boolean).map((line)=>JSON.parse(line) as Row);if(invocation.args.execute!==true)return {exitCode:0,stdout:['Resolved cleanup replay plan validated; execution was not requested.'],stderr:[],report:{command:'guarantees campaign-cleanup',ok:true,mode:'plan',commands:entries.map((entry)=>command(entry))}};try{for(const entry of entries)run(context,root,'cleanup-replay',entry);return {exitCode:0,stdout:['Campaign cleanup journal replay completed.'],stderr:[],report:{command:'guarantees campaign-cleanup',ok:true,id,generation}};}catch(error){return {exitCode:1,stdout:[],stderr:[error instanceof Error?error.message:String(error)],report:{command:'guarantees campaign-cleanup',ok:false,id,generation}};}}
